### ISSUE TITLE
Voyant Exercise: Post a Visualization from Voyant Tools here

### ISSUE THREAD

**Issue by ebeshero** [newtfire/introDH-Hub#11]
Experiment with <a href="https://voyant-tools.org/">Voyant Tools</a> on any collection of data from our annotations, or from the readings themselves. Post a visualization and explain what you did to create it on our introDH-Hub Issues Board here. Capture some embed code for putting your visualization on a website and include that with your post.

**Comment by ebeshero** [comment]
For those who need it: here is a direct link that you can access from your Penn State Google accounts to my Google Drive folder for DIGIT 100. One of the sheets you may find there contains all 546 of our annotations. You can make a copy of it and try sorting it as you like to organize by a column, say by tags: 
https://drive.google.com/drive/folders/1vH4FCZp2nKT9szBQoJnja4-uesA_e0G8?usp=sharing

**Comment by am0eba-byte** [comment]
[This Vast Conspiracy of Memory Voyant Visualization](https://voyant-tools.org/?corpus=fa519561ab971556f3e4185e90281306&visible=155&view=Cirrus)

![VastConspirMem_Voyant](https://user-images.githubusercontent.com/70165410/94740032-ebdec400-033f-11eb-821f-1f791708dfb9.png)

I was able to create this lingual visual by painstakingly highlighting the entire text of Khalid Warsame's "The Vast Conspiracy of Memory" and copying the essay into Voyant's text bag box. Below is the corresponding embed code Voyant gave me to embed this visualization in an HTML website like Wordpress:

```
<iframe style='width: 818px; height: 341px;' src='https://voyant-tools.org/tool/Cirrus/?visible=155&corpus=fa519561ab971556f3e4185e90281306'></iframe>
```

**Comment by ypl5391** [comment]
https://voyant-tools.org/?corpus=68a61e7cd8ea132cdae4c9c19cb7d894&view=Cirrus
I create this by put the annotation "Colonialism is the exploitation of another country for economic gain, however this practice stems from another called Mercantilism. Mercantilism is the theory that there is a limited amount of wealth in the world and ones own country needs to maximize exports and limit imports thus leading to Colonialism in order to acquire more wealth for the mother country and increase its exports." in the Voyant tools.

**Comment by arrowarchive** [comment]
I used _Voyant _Tools__ to create a chart of everything under the "Text" column from my spreadsheet (the text, as in, what I wrote in my annotations). Judging by my URL, I appear to look at things from an analytical standpoint, as I use the words "people, know, and examples" in a lot of my annotations. People was used the most, having used it in 17 times over the course of 28 annotations, and I would compare my own outlook of the articles to similar things I have seen or heard about in real life. 
https://voyant-tools.org/?corpus=5e3e7813464d195940a1113979e72760&visible=75&view=Cirrus

**Comment by dxh405** [comment]
I took the "LinguaCelta - Leaving Humanist" article we read and put it into Voyant. I played around with a bunch of the tools and settled on the "Links" tool. This tool gives you words that were linked with other words in the article. If you double click more words appear and give you even more context and what other key words were being used along with it. 
https://voyant-tools.org/?corpus=2a8556d1b5d13e8b042a5bf4906b9722&query=humanist&query=list&query=post&query=racist&query=asserting&query=mailing&query=08&query=acts&mode=corpus&view=CollocatesGraph

**Comment by Meganpeck115** [comment]
I accessed the "Virtual Machine configuration" article we read and annotated, and inserted the entire article into the Voyant tool. Many tags appeared and also a graph of the relative frequencies among other things as well. What interested me the most were the common used words that you could adjust. Here is the link to access what I have been seeing. 
https://voyant-tools.org/?corpus=dd773d4ee2db5b24a1da673bbe9f9835

**Comment by amw6765** [comment]
<img width="1014" alt="Screen Shot 2020-10-02 at 2 13 02 PM" src="https://user-images.githubusercontent.com/70722523/94955993-6e3ec380-04b9-11eb-9158-5703c942c1a4.png">
I started by copying and pasting all of the quotes that my peers and I had posted. It is very interesting to see the different words that stood-out most when I did this. Ass you can see 'https' is the biggest and most frequent word that was detected. This is because all of the pictures we added in our annotations turned to links when I copied them down. Other than that you  see words like technology, people, data, computer. I find this super fascinating and in depth. This website allows you to dig very deep in different connections that all of the data had in common.

**Comment by bpm5520** [comment]
![WordCloud](https://user-images.githubusercontent.com/70908691/94960290-a39adf80-04c0-11eb-939b-2d8e3f352c98.png)

I took all of the annotations that I made and put them into Voyant. My most used words all had to deal with technology or computers, with both of those words even making multiple appearances. It's interesting that I mostly annotated things that I found the most interesting, being the computers, code and technology that were discussed in the articles.

<iframe style='width: 637px; height: 458px;' src='https://voyant-tools.org/tool/Cirrus/?corpus=fb3b457920017fc1ac8851c7ea6431f7'></iframe>

**Comment by nxh5137** [comment]
[voyant tools](https://voyant-tools.org/?corpus=8f238e6b4e402ce99c8d2a83cf95ff77&view=Cirrus)
I was able to make this by copying and pasting the link of '[This Vast Conspiracy of Memory](https://meanjin.com.au/essays/this-vast-conspiracy-of-memory/#annotations:15QOovChEeqm0g-Ika0MNA)' and then exporting the link to the lingual visual, and copying and pasting it into a hyperlink

**Comment by gabbiedoster** [comment]
<img width="853" alt="Screen Shot 2020-10-02 at 3 27 39 PM" src="https://user-images.githubusercontent.com/70911505/94962100-e5795500-04c3-11eb-9c16-47ed1c15d588.png">
I copied all the text and pasted it into Voyant that the class used from the article, "Making Things and Drawing Boundaries". There were a total of 101 annotations. With Voyant Tools I found that the word "technology" was most used among the annotations. It was used a total of 26 times! Another popular word used 19 times was "digital". I found further analyzing the data we already used in Hypothesis was super interesting.  
Link to voyant tools data:
https://voyant-tools.org/?corpus=39b77cfa7570da3f8a77fb26089a8560

**Comment by natalyamyers** [comment]
<img width="390" alt="VoyantTools" src="https://user-images.githubusercontent.com/70730578/94963916-d3e57c80-04c6-11eb-891d-dbd5feb286ad.PNG">
I created this word cloud by pasting the link from the article "This Vast Conspiracy of Memory" <br>

I moved the number of words included to 195 so that I could compare the types of words that were most used to those that were used less frequently. All of the smaller words were all used at least 2 or 3 times. It was funny to me to see the contrast of bigger words like "body" (19 uses) and "mind"(23 uses) to smaller words like "bumblebee"(2 uses) and "murder"(6 uses). <br>

Thinking back to the content of the article, I can't remember much from the two lower used words (very obviously, because they weren't used very frequently) but it's funny to see words that I think would stand out so much to me and not remember much from them. Even though body was one of the higher used words, I also don't think that I could remember a specific piece of the article that used it even once. <br>

I think it's interesting that looking at the whole word cloud I could very quickly tell you which article it came from, but if you gave me one of the top words I would have no clue.

**Comment by NickyV1234** [comment]
![download](https://user-images.githubusercontent.com/70916831/94965031-bdd8bb80-04c8-11eb-8e03-bb771e3d0905.png)
here is all the phrases I was able to see for one of our first readings in the semester "The Inequities of our Remote Gathering Meeting Tools". When I first created it I didnt really see too many terms so I used the slider tool to increase the amount of terms to around 180

**Comment by mws6176** [comment]
I took all of the annotations from the passage, "The Inequities of our Remote Gathering Tools". The most used terms ended up dealing with the accessibility of zoom or similar programs. I decreased the number of terms as to see only the top of the most common. 
https://voyant-tools.org/?corpus=6d5d34f0ca8408fa093d6ac15f55fd68&visible=75&view=Cirrus

**Comment by jzm6677** [comment]
I created a world could using the Voyant Tool by taking the tag column are spreadsheet for hypothesis.is.  I used the tags created by the everyone in the class.

https://voyant-tools.org/?corpus=df08ca837486bc09dadf5b9ca4d54d10

**Comment by tomsheehy** [comment]
![Screen Shot 2020-10-02 at 9 42 14 PM](https://user-images.githubusercontent.com/70911575/94980478-2ee39780-04f8-11eb-9095-9661d07d5b6d.png)
I took the url's from 3 of my September annotations and pasted them into Voyant Tool. I found that "digital" was the most used word in my annotations and was used 68 times. There are a lot of computer related words. When I used the slider tool, it seemed like a lot of the words are used a common amount of times. 
The embed code I got from Voyant is: 
<iframe style='width: 401px; height: 366px;' src='https://voyant-tools.org/tool/Cirrus/?visible=105&corpus=59881ea9886f12007eff5c6cf88afb21'></iframe>

**Comment by pxl5083** [comment]
I took the entirety of my three favorite articles:
"What is Code"
"The Making Of A Digital Humanities Neo Luddite"
"The Vast Conspiracy of Memory"

This is what I got:

https://voyant-tools.org/?corpus=67ddcd77b36701424abcafafc4943d58&view=Cirrus

**Comment by xsierraallen** [comment]
I copied the URL from the Lingua Celta article on Hypothes.is and pasted it into the Voyant Tools search engine. I was able to select a visual and find the embedded code for [https://voyant-tools.org/?corpus=4244a6e4895ff64101d018872717b29d&visible=85&view=Cirrus](url)
![voyant-logo-tiny](https://user-images.githubusercontent.com/70916885/94981568-46734e00-0501-11eb-8248-86601d83f26b.png)

**Comment by BenS6206** [comment]
I got this by copying all of our annotations for the article "The inequities of our remote gathering tools". It's worthy of note that things like "aug" are in here because each post had a header including when it was posted. https://voyant-tools.org/?corpus=134971b5a0cae12204f342778923eaad&documentFormat=SOURCE&documentFilename=&view=Documents

**Comment by hjl5363** [comment]
I copied this article URL into Voyant Tools to have a visual created for me. I discovered that one of the most frequently used words was location. https://voyant-tools.org/?corpus=240699f40dbcffa151fd6c42a07013fe<img width="596" alt="Screen Shot 2020-10-03 at 12 28 38 AM" src="https://user-images.githubusercontent.com/70916576/94983341-d4563580-050f-11eb-9cca-bfc5a8255633.png">

**Comment by kzp308** [comment]
![voyant](https://user-images.githubusercontent.com/70867065/94984864-cd82ef00-051e-11eb-94be-8e60d335e381.png)
I entered the URL of our reading, LinguaCelta. Humanist was the most used word. It was used 15 times. Quite a few words shared the lowest counts. This includes affect, academic, apparently, etc.

**Comment by JesseBeckwith1998** [comment]
![Voyant](https://user-images.githubusercontent.com/70914661/95130172-2b375700-072a-11eb-9ef1-c69f4c972275.jpg)
 I entered the text from the Digital Humanities Luddites and boundaries article excluding the notes and bibliography in order to focus on the actual article. The most used words were DH, Digital, and Humanities. I find it fascinating how the author used DH to shorten digital humanities and still ended up having them as the 2nd and 3rd most used words in the article.

**Comment by tomsheehy** [comment]
I entered the text from one of our readings on Virtual Machine Configuration excluding the bibliography. I discovered one of the most frequently used phrases was "you can".

![Voyant3](https://user-images.githubusercontent.com/70911575/95157117-27c1c100-0766-11eb-805a-d367126b5fb6.JPG)

**Comment by hjl5363** [comment]
I did analysis on an article from the New York times regarding the COVID-19 pandemic and the increase in cases in the midwest. One of the most frequently used words that was not surprising to me was "Trump". A lot of controversy and drama has come towards him.

[
<img width="1792" alt="Screen Shot 2020-10-13 at 8 58 25 PM" src="https://user-images.githubusercontent.com/70916576/95931589-9373e180-0d97-11eb-8c11-4b52ad84fe52.png">
](url)
