### ISSUE TITLE
Workshopping views from Voyant / Antconc

### ISSUE THREAD

**Issue by ebeshero** [newtfire/introDH-Hub#14]
Post some screen captures of your findings playing around with Antconc and/or Voyant Tools with combinations of texts available on our [Corpus Analysis Assignment](https://newtfire.org/courses/introDH/AntConAssign.html)! As you post, tell us a little about what you think is interesting!
* What questions come to mind as you look at the frequently used ngrams?
* How does one text seem to differ or compare with a different one?

**Comment by arrowarchive** [comment]
@ebeshero, I used _AntConc_ to compare _Frankenstein_ and _Hamlet_, and I noticed something very similar between the two: the phrase "in the" is in the top three for each one, but after analyzing it further, the phrases are used differently in each story (see below: _Frankenstein_ is on the left, _Hamlet_ is on the right)

![compare1](https://user-images.githubusercontent.com/70866633/95494405-e00c8680-096b-11eb-8670-dd2f69829a5e.jpg)
![compare2](https://user-images.githubusercontent.com/70866633/95494414-e438a400-096b-11eb-9685-69b5207187c1.png)

In _Frankenstein_, the term is used for dramatic emphasis. A lot of adjectives follow the phrase to make the scene more dramatic (and having read _Frankenstein_ myself, the story is very wordy). In _Hamlet_, the phrase is used for exposition. For the majority of the list, the phrase is used to describe the setting or to draw comparisons from one thing to another. 

**NOTE:** I have a dual-monitor setup, so I cannot crop out the black in the second screen. If there is a way for me to take a photo of a single screen without having to crop out the other, please let me know!

**Comment by Meganpeck115** [comment]
I found _AntConc_ was a tad easier to use. I used two different articles. One was an Adobe photoshop article (top) and the other was a Adobe lightroom article (bottom). I saw that the ngrams in the first s=article contained a lot of hyperlinks until I began to scroll down and I could not quite understand why as my second one did not. The second article contained the words "red, green, blue, red" frequently just like the first one as well.

![image](https://user-images.githubusercontent.com/70918396/95600801-a184d380-0a20-11eb-82b9-22315619ffe9.png)

![image](https://user-images.githubusercontent.com/70918396/95601484-84043980-0a21-11eb-9a4c-b3bbb7b29874.png)

**Comment by tomsheehy** [comment]
I used _Antconc_ to compare _Dracula_ and _Macbeth_. I quickly discovered that _Antconc_ is very user friendly and efficient for comparing articles. During my comparison, I learned that _Macbeth_ heavily used "Lady Macbeth", making it the most frequent used pair of words in the article with 71 times. Although her name may be used in stage settings, it shows how important Lady Macbeth's role is in this tragedy. This was still surprising to me because in other articles, phrases with the word "the" or "a", are typically the most frequently used. For example, in _Dracula_, the most used phrase was "of the" being used 891 times.
![ANTCONC_Dracula](https://user-images.githubusercontent.com/70911575/95605546-1c50ed00-0a27-11eb-9de4-b63d2f24b229.JPG)
![ANTCONC_Macbeth](https://user-images.githubusercontent.com/70911575/95605550-1ce98380-0a27-11eb-8438-27d2e3d1833a.JPG)

**Comment by dxh405** [comment]
I chose Dracula and Frankenstein as my two text files. I figured since they are both about "monsters" in a way there might be some interesting similarities between the two. Immediately once putting both through AntConc I discovered both had the phrase "of the" as the most frequent phrase. 
![of the](https://user-images.githubusercontent.com/70723878/95606636-9a61c380-0a28-11eb-8f26-200f96d65618.PNG)

I then decided to look at the word monster in both of the books. It appears that in Frankenstein, the word monster was used to describe someone or something more often than in Dracula. In Dracula, monster was used to describe something inanimate more often than a person, for example "monstrous waves". That does make sense as Frankenstein is literally a "monster" in a sense, where vampires are vampires, not necessarily monsters.  
![monster](https://user-images.githubusercontent.com/70723878/95606910-017f7800-0a29-11eb-9456-e1b9ab689c72.PNG)

**Comment by bpm5520** [comment]
I compared Dracula and Pride and Prejudice since they were both 19th century novels. With a limit of 2 word long n-grams, both had "of the" show up as the most in both works. As well, within the top 6 on both of them, it shows what I assume to be main characters of both, as "Van Helsing" and "Mr Darcy" show up hundreds of times in each respective work. I also compared them by 5 word long n-grams, which showed a key feature to Dracula. Each chapter of Dracula is set by a journal or diary entry, shown by the journal and diary entry n-grams being the top of the charts. Meanwhile in Pride and Prejudice, there seemed to be no real correlation to the top entries, mainly more common phrases and a handful of characters involved.

![Comparison1](https://user-images.githubusercontent.com/70908691/95608339-f9283c80-0a2a-11eb-8e03-82c742c99e67.JPG)
![Comparison2](https://user-images.githubusercontent.com/70908691/95608342-f9c0d300-0a2a-11eb-97c3-8712dda7ff2a.JPG)

**Comment by amw6765** [comment]
<img width="1095" alt="MarlowFnT_NGram" src="https://user-images.githubusercontent.com/70722523/95611554-f9770680-0a2f-11eb-9d79-12acfcf5f66d.png">
After comparing the two different story .txt files of Marlow in AntConc, I was able to see some interesting similarities and differences. The N-Grams between the two seem to be mainly different from one another. Fatstus seems to have more clustering of words that deal with good and evil. As well as a lot of talk about good and bad angels. Where, Tamburlaine appears to have more clusterings of god and kings. There was one apparent N-Gram that both stories do share using the minimum of 3 words and maximum of 6 (ex. 'all the world' is an N-Gram used in both) I am quite certain that if I mess around with the constraints even more, I will be able to see more similarities between the two.

**Comment by AlexanderRAnderson** [comment]
I used *AntConc* to compare Shakespeare's works, *Hamlet* and *Macbeth*. I was interested when I saw the "words", "s" and "d." Turns out they are just the contractions he used. I still thought I could find something interesting by looking at these contractions. I found that Shakespeare used contractions more frequently in *Macbeth* than in *Hamlet*. *Macbeth* was written in 1606 while *Hamlet* was written in 1609. I found this interesting because Shakespeare seems to use less contractions in the newer work. This may imply that he stopped using contractions as often later in his career, but I cannot be sure until I look at more of his works.
![Comparison](https://user-images.githubusercontent.com/61561118/95614380-41d7f980-0a1b-11eb-8756-0150f5301dfb.PNG)

**Comment by kzp308** [comment]
I found that AntConc was easier to use for this type of comparative exercise. I used Dracula and Frankenstein to be compared for this exercise because I think it's in the spirit of October to do scarier works. I let there be a two word minimum and maximum. When I put Dracula into AntConc, I found that the most frequently used words were "of the". It was used 863 times in the text. When I put Frankenstein into AntConc; coincidentally, I found that the two words most frequently used together were "of the". I thought this was really interesting to learn about. Even though the words don't seem that important, they are. 
![Screenshot (36)](https://user-images.githubusercontent.com/70867065/95616369-ad2fc480-0a37-11eb-9c9a-9a55ad48122b.png)
![Screenshot (35)](https://user-images.githubusercontent.com/70867065/95616373-adc85b00-0a37-11eb-97c2-90bf3ad032f7.png)

**Comment by BenS6206** [comment]
I examined Macbeth vs Hamlet to see if there were any differences in word usage between the two plays and found them to be more similar than I expected. The most frequen N-grams are pretty much the same in both and are fairly common sets of words. I was hoping for something a little more interesting considering the works being analyzed, perhaps increasing the maximum amount of words in each would create more interesting results. 
![image](https://user-images.githubusercontent.com/69773455/95617760-ec5f1500-0a39-11eb-8b14-de071d471f96.png)
![image](https://user-images.githubusercontent.com/69773455/95617959-3c3ddc00-0a3a-11eb-815f-0558e267c8b6.png)

**Comment by nxh5137** [comment]
I compared _Frankenstein_ and _Pride & Prejudice_ in AntConc to see if there were any similarities to the two stories, looking at how frequent the words were used and saw similarities between the two. I had the N-Gram Size at a min. of 2 and a Max. of 4. 'of the' is the most frequent of the words in many sentences as you can see in the pictures below frequently used 990 times. 
![Screenshot (17)](https://user-images.githubusercontent.com/34407859/95615324-e9a1f700-0a1c-11eb-87f5-fad93cfca5d8.png)
![Screenshot (18)](https://user-images.githubusercontent.com/34407859/95616782-3daddb00-0a1f-11eb-98c8-f8764e360363.png)

When I looked deeper to find any other words that were not the same generic words in a sequence that anyone can find in any kind of writing out, I stumbled upon a character that appears in both stories. 'Elizabeth was' appears in both stories that have nothing to do with each other. Most likely a coincidence since there is a big age gap between the two making the chance of them seeing each other incredibly slim, but Shelley might've gotten the name from Austen.
![Screenshot (21)](https://user-images.githubusercontent.com/34407859/95618361-c3328a80-0a21-11eb-9950-ece51c512a3e.png)
 
![Screenshot (23)](https://user-images.githubusercontent.com/34407859/95618393-d2b1d380-0a21-11eb-925d-bfe7bbba0173.png)

**Comment by NickyV1234** [comment]
The two texts that I analyzed were Charlotte Brontë, Jane Eyre and Emily Brontë, Wuthering Heights. one of the key things that I had realized was that one of the n grams that showed up was phrases that used bonnet. even though bonnet wasnt the most used word there were the most different types of phrases that it was used in.
![20201009_150215](https://user-images.githubusercontent.com/70916831/95622207-03553580-0a41-11eb-9fb0-f556bca97643.jpg)
![20201009_150222](https://user-images.githubusercontent.com/70916831/95622212-051ef900-0a41-11eb-88d8-d98274a87053.jpg)
![20201009_150236 1](https://user-images.githubusercontent.com/70916831/95622216-06502600-0a41-11eb-86f1-b93d57a1a5c2.jpg)

**Comment by jzm6677** [comment]
I used AntConc to look at Macbeth and Pride and Prejudice a n gram i saw often was in the.
![2](https://user-images.githubusercontent.com/70913490/95624183-7318ef80-0a44-11eb-9da2-6aee9302c7e4.png)

**Comment by am0eba-byte** [comment]
Here's my tardy entry:
I decided to clean up and use Alice in Wonderland by Lewis Carrol and Dante's Inferno to compare through Antconc and Voyant. I know, they couldn't be more different pieces of literature: one's an Italian poem-epic(I used an English translation) and one is an English childrens' novel. I thought it would be interesting to explore these two because their stories draw some interesting parallels - both of the main characters are going on a journey through fantastical realms (Hell and Wonderland), and both of them meet other characters within these realms that either help or hinder their journey. Here are the screen captures I gathered from them on Antconc:
### Alice in Wonderland 3-gram

![alice_3gram_antconc](https://user-images.githubusercontent.com/70165410/95627504-5384c580-0a4a-11eb-8173-3a76196dacc3.png)

### Alice in Wonderland 4-gram

![alice_4gram_antconc](https://user-images.githubusercontent.com/70165410/95627566-68f9ef80-0a4a-11eb-99ad-1fbe6b140b28.png)

### Dante's Inferno 3-gram

![inferno_3gram_antconc](https://user-images.githubusercontent.com/70165410/95627628-7dd68300-0a4a-11eb-9633-efcb16aaeea6.png)

### Dante's Inferno 4-gram

![inferno_4gram_antconc](https://user-images.githubusercontent.com/70165410/95627705-a199c900-0a4a-11eb-9cca-479497721c6d.png)

Comparing the 3-grams, I thought it was interesting how little Dante's Inferno has word frequencies containing "he said," or "I said," or "[character] said" as opposed to Alice in Wonderland. I think this reflects how often Alice's crazy character creatures verbally interacted with her, while in Inferno, Dante's demonic and hell-dwelling encounters were a bit less verbal - and Dante had a much different way of expressing character interactions, as I could sort of deduce from the 4-gram. Instead of saying "'yada yada,' said Virgil" he writes "'yada yada,' and he to me 'yada yada yada'" Maybe because it's originally in Italian, and it's * super old * Italian, so even stranger.

Here's the Voyant Word Clouds:

### Alice in Wonderland
![alicewonderlandCloud](https://user-images.githubusercontent.com/70165410/95629417-e70bc580-0a4d-11eb-9a1b-b9529954530b.png)
### Dante's Inferno
![danteinfernoCloud](https://user-images.githubusercontent.com/70165410/95629425-ebd07980-0a4d-11eb-8b58-48bb99bf37ce.png)

This was pretty nifty - both of their most frequently used word was "said," which strangely isn't obvious in Inferno's n-grams. Also, you can definitely date Inferno by looking at this word cloud and noticing the frequent prevelence of "doth," "unto," and "shalt".

**Comment by gabbiedoster** [comment]
I decided to compare Shakespeare's _Romeo and Juliet_ (left) to Jane Austen's _Pride and Prejudice_ (right). In doing so, I found the n-grams of both the play and novel. In Shakespeare's _Romeo and Juliet_ most of the n-gram terms are individualized compared to the n-grams in _Pride and Prejudice_. One n-gram that's used frequently in both texts is "i am". Another discovery I made was most n-grams in the text of _Pride and Prejudice_ are in past tense or referring whereas in _Romeo and Juliet_ n-grams are present tense. This easily may be the explanation of the tenses the book and play were originally written in.
<img width="1382" alt="Screen Shot 2020-10-14 at 2 33 32 PM" src="https://user-images.githubusercontent.com/70911505/96030675-4b51cf00-0e2a-11eb-9ab3-f1ad68b99d18.png">
