### ISSUE TITLE
Frankenstein Variorum Micro-Comparison Exercise

### ISSUE THREAD

**Issue by ebeshero** [newtfire/introDH-Hub#22]
Look at the following combinations in the [Frankenstein Variorum Viewer](https://frankensteinvariorum.github.io/viewer/viewer/): 

1) Version Thomas: Section 8: first full paragraph: Click on the two boxes highlighted and look at how the editions compare at each highlighted moment. Do you see any problems with what's being represented here? 
<img width="651" alt="Screen Shot 2020-11-04 at 3 09 47 PM" src="https://user-images.githubusercontent.com/4014518/98162782-dbc28300-1eaf-11eb-8ad7-4246c3199675.png"> 

2) Version 1831: Section 8: Scroll down to long dark-grey passage: "in a rather too philosophical and connected a strain..." Look at the passages following in the screen capture. Can you describe how the Frankenstein narrative was changing from the MS through the 1831 editions at this point? 
<img width="669" alt="Screen Shot 2020-11-04 at 3 17 12 PM" src="https://user-images.githubusercontent.com/4014518/98163581-0103c100-1eb1-11eb-9285-1b0cc85f6340.png">

3) Version 1818: Section 5: There are not many revisions here, so look across the entire section and study it. Can you describe how the Thomas copy would have altered this section, and how the 1831 edition altered it differently?

4) Version 1818: Section 7: This is where the Manuscript first begins, and also where there are lots of revisions in the last version, 1831. Take a look at this passage in the Variorum and click on the highlighted passages. Do you notice any problems or moments of interest in the way the comparison moments are represented here? 
<img width="651" alt="Screen Shot 2020-11-04 at 3 23 46 PM" src="https://user-images.githubusercontent.com/4014518/98164248-feee3200-1eb1-11eb-8da0-3e53ddca4d91.png">

**Comment by NickyV1234** [comment]
group 1 Nicky, Mia, Daniel, Anthony, Jalen

#1. for the highlighted section "misery, Elizabeth" if you replace it with the ms version the end of the edit becomes repetitive with the un altered lines. "Elizabeth had caught the scar  had caught the scarlet fever"

#2. In the 1831 version, the narrator was more passionate about explaining his youthful years, whereas the other four versions dont see it essential to describe.

**Comment by arrowarchive** [comment]
I'm in group three with Natalya, Peter, and Kyara, and we studied section five of the 1818 edition of _Frankenstein_. We came to an agreement that this version was easy to read, as the setting was described in terms we understood while providing a clear picture. 

The Thomas version made larger changes, but in small quantities. Most notably, an entire paragraph (pictured below) was rewritten and expanded upon the details in the story. Aside from this revision, the Thomas version was similar to other versions of the story.
![Screenshot (121)](https://user-images.githubusercontent.com/70866633/98168250-4f688e00-1eb8-11eb-8e3f-20f7d598021c.png)

The 1831 version made multiple small changes in the form of spelling, punctuation, and grammatical changes. The only exception was towards the end of the section, where two sentences were rewritten. 
![Screenshot (84)](https://user-images.githubusercontent.com/70867065/98168784-17157f80-1eb9-11eb-9929-9d2116d428f1.png)

**Comment by Joelpie** [comment]
Howdy, I'm representing group #2. 

We found it interesting that this entire paragraph of context and backstory was not including until the 1831 edition of Frankenstein. Up until this point, the prior sentence concluded with just the word "doctrine" (and even this was reportedly absent in the original edition). The word doctrine stayed from 1818 until it was replaced with the vast chunk of text highlighted gray in the excerpt. 
![image](https://user-images.githubusercontent.com/60297307/98168668-eaf9fe80-1eb8-11eb-946c-b15a43011a93.png)

**Comment by gabbiedoster** [comment]
Group Four (Gabbie, Harrison, Thomas, & Yuchen)
Answering Question #4:

Some moments of interest our Breakout room found in the 1818 Edition in Section 7 was many of the common word choice was found to be similar with also the 1823 and the Thomas Editions of Frankenstein. The Mary Shelley version slightly differed in its own way and had similar word usage. What we found most interesting is the 1831 version was had highlighted passages that were very different from the other editions. In the first highlighted line, "Every one adored Elizabeth", was written in much greater detail in the 1831 Edition. A wapping paragraph talking about Elizabeth in detail, her character and role within the story was described. Rather than just addressing her normally in the other editions, the 1831 version brings her character to life. 
<img width="346" alt="Screen Shot 2020-11-04 at 4 13 56 PM" src="https://user-images.githubusercontent.com/70911505/98168601-cc940300-1eb8-11eb-95fb-d3a1b716916d.png">
