### ISSUE TITLE
Remediation, Remixing, and Copyright Discussion

### ISSUE THREAD

**Issue by ebeshero** [newtfire/introDH-Hub#29]
First, read the following:
<ul>
                        <li><q><a href="https://www.wipo.int/wipo_magazine/en/2015/03/article_0006.html">Remix Culture and Amateur Creativity: A Copyright Dilemma</a></q></li>
                        <li><q><a href="https://fairuse.stanford.edu/overview/fair-use/four-factors/">Measuring Fair Use: The Four Factors</a></q></li>
                        <li><a href="https://creativecommons.org/">Creative Commons</a>: explore the site, look at <a href="https://creativecommons.org/use-remix/">Use &amp; remix</a> section</li>
                     </ul>

Then respond to one or more of the following prompts for our class discussion:
* What issues have you personally seen with remediation and fair use? 
* What "grey areas" can make copyright infringement unclear?
* What is Creative Commons about? Would you license your own work using Creative Commons? Why / why not?

**Comment by arrowarchive** [comment]
I feel as if references are a frequent cause of fair use issues. Pose references are essential for me, and there was a time where I used _Pinterest_ as my pose reference source. When I found a pose I wanted to draw, I would check the source and a surprising number of images I had saved explicitly mentioned that the artists didn't want others using the image (since the poses were from "your character here" posts, where people could purchase to have their character in the picture). Going back to _Pinterest_, people were reposting the templates and people were using them with no knowledge of the original artist's intentions.

      I left _Pinterest_ a few months later after witnessing images I had saved for references posted by other users be taken down for copyright infringement (being notified that it was pulled from my images) and I found a safer source for pose references. Their only requirements are that if the original image is shared somewhere or manipulated, that credit must be given to them. If the image is used solely as a pose reference (which I was doing), then providing credit was optional but greatly appreciated. The artist's page is even issued under a Creative Commons license, but it's the most lenient one available.

     Creative Commons is a form of copyright protection for a user's work. There are six licenses available that influence how others may share your work. I'm considering using a Creative Commons License because the majority of my work is original content. When sharing it online, it's easy for someone to claim it as their own and potentially profit off of it. I would want to put a license in place that would forbid commercial use of my characters (with the sole exception being the artists I commission), but they would have a rule to follow: **If they want to share the commission online, they must ask me first and credit me for the original design if my characters are used.** 
     
     It was in a discussion that I realized "commissions are technically non-commercial, since another person is drawing something at the request of the creator, who will use it non-commercially (profile pictures, desktop backgrounds, posters, etc.) unless they say otherwise. I want to ensure that my own drawings are protected from misuse, but also that anyone whom I commission to draw my characters for my personal use won't get in trouble with the system, especially since a lot of my characters will likely be used in animated productions I make later down the line.

**Comment by nxh5137** [comment]
A grey area I noticed that made it unclear to me was what and how much you could use. For example, the less you take, the more likely you'll be excused. However, if you a small amount of what might be considered the heart of it, that won't be considered fair use. I might get this if you claim you wrote _Dune_, but if you are using a scene as a homage, would that be under fair use?

**Comment by kzp308** [comment]
A grey area I noticed when I read is how Canada is one of the only countries who has moved this new exception into place. When people remix things, often their intent is to express themselves creatively. They are not trying to rip off the song or take away from it. If I were one of the artists and just heard my music in a remix of songs, I would likely be flattered. Not only would I feel this way, but if someone is using my music for a remix, my music suddenly reaches their audience. It could help my music career in a way. I understand why artist can be upset at this though. They spend countless hours working on their songs. So, I understand, but I feel like if they say who wrote the song and the name of it, the authors should be more calm about it.

**Comment by AlexanderRAnderson** [comment]
I know there has been a lot of issues with copyright claims in the online entertainment industry. Every online video/streaming platform such as YouTube and Twitch have had issues with copyright claims. YouTube has an algorithm which detects copyrighted music and has a manual claim system that allows people to claim other people's videos. The issue arises when there is a clear case of the video being within fair use but YouTube allows it to be demonetized and claimed regardless. The issue Twitch has been having is that the music industry has been coming down on Twitch because people usually play songs when they stream. These streams are kept up as videos after the stream has ended. Twitch has been pressured by the music industry to punish streamers for having copyrighted music even though sometimes it is well within fair use. These grey areas will have to be figured out if copyright wants to be handled correctly.

**Comment by dxh405** [comment]
Creative commons is all about how you would like your work to be received and used. If you are all about putting your work out there you want to have some sort of licensing to attach to it to give some structure to how it can be used. I really cannot see a downside to using creative commons for your work. If you want your work to be used and looked at and changed for the betterment of a community, there is no harm putting a creative commons license on it for that and it can add some guidelines to how it can be used. 

Also the issue of the grey area is a complicated and hard to answer one. Having black and white areas on an issue is common, what is not as common is that if the grey area between the two is significantly larger than the black and white sections. This is what we have with the current copyright infringement problem. The grey area is so big that many people (especially those in online content creation) do not have a solid answer of what to do, leaving many people out to dry so to speak. With how rules are constantly changing and contradicting each other you have a lot of trial and error that leads to even more problems. It is a mess that has no solid definitive answer at the moment and it does not look like a solid answer will be given in the future.

**Comment by bpm5520** [comment]
With myself always finding someone on YouTube or Twitch to watch, I am unable to escape the tightrope that creators walk for using fair use and keeping in mind copyrights. There is always some drama going on with Youtubers about copyrights, and they have to be very careful when using music or playing games. Nintendo has been fairly strict on their use of copyright, striking down parody videos and channels, and even rom hack creators who work off of Nintendo video games like Pokémon and Mario can get lawyers in their inbox giving them cease and desist papers. Music labels will come after streamers for simply having a 10 or 15 second clip of their music in the video and will monetize that video for themselves. The copyright holders have so much power, and yes they do deserve to do what they want with their own content, but some can take it to big lengths and completely bar any content creator from ever using their products, even if they put a completely new spin on it (like parody accounts).

**Comment by xsierraallen** [comment]
Copyright infringement occurs when an artists work is copied and reproduced in some way and that artist did not give their consent. This work can be performed, reproduced or remixed, and displayed in some way. What makes this a grey area is that not everyone has the same opinions or intentions on copy right. Not everyone who copies a piece of work is doing it with bad intentions, many times artists are just inspired and they make something of their own. Often times credit is due to those who have earned it. The people that copyright could in fact be trying to help the original artist in some way. When an artist remixes a song, credit is often seen on the title of the track. If were talking about products such as the cabbage patch kids and the garbage pail kids, I am not sure if garbage pail kids give the original credit to the other company, but you are clearly able to see that the garbage pail kids are a spinoff from the original. There are many grey areas and there is nothing to tell us what is right or wrong because everything is based off of opinions and true intentions.

**Comment by tomsheehy** [comment]
A grey area I noticed that could be cleared up would be using songs in videos for social media platforms. It is very common to see influencers removing their media or content because of copyrights. Not to mention the strictness from platforms on cursing in content or videos. It seems odd as to why because of the free publicity that is offered when using music that others have created. When songs are played on videos I believe that it means the creator of the new content is interested in the original creation. This could be seen as a compliment by many. Often times, it is people's jobs to create content and they are penalized for giving free publicity to others. If social media influencers wanted to create content with original ideas, then this greyed area would need to be solved with copyright infringement.

**Comment by natalyamyers** [comment]
I think for me I get confused on the grey areas of copyright when it comes to infringement on something that somebody claims to be their idea or something that they created. Especially in the world of creative arts, I find it hard to believe that it's not possible for two people to have the same, or similar, idea. How far can you go with claiming "ownership" over something, and how similar is too similar? And along with that, who gets to decide if two things are just dissimilar enough to not warrant copyright infringement?

**Comment by amw6765** [comment]
The biggest example of remediation and Creative Commons is its use in YouTube. The guidelines and the control that YouTube has is quite significant. They have algorithms that are able to detect and flag just about any type of work that happens to licensed. This is something you hear YouTubers talking about quite often. A lot of videos of theirs are either taken down or become demonetized from issues with copyright. Because of the sensitivity of their algorithms even a split second slip-up or even a person or car that may be driving by playing music only for a glimpse of time will be grounds to flag their work. YouTube takes these things very seriously and almost always the fault of the user was not intentional. I believe this to be one of the gray-areas with this sort of thing. However, by accepting the terms and conditions and being a content creator on their site you have to be careful and aware that these things are real and do happen. 

Personally for my type of work I would like to have it protected by type CCL. I would not wish for adaptations of my work to be permitted and used for someone else's benefit. I also do not and would not like for someone to use my work and possibly make it commercial for the web to use and have the option to make money off of my hard work and skills.

**Comment by JesseBeckwith1998** [comment]
an example of a copyright issue I have seen is that from Twitch. Recently they have added a new system to detect copyrighted property used in streams. Many of the large streamers had to delete their video logs from past streams because they did not want to receive a ban for violating the rules. 
A grey area I can see in the copyright infringement is that of "Fair Use". If I put a disclaimer on a video decision that I do not own the song used I am less likely to receive a lawsuit than if I do not include it even though I am still breaking copyright law. 
Creative commons is a site in which content creators and license their intellectual property through creative commons with many different licenses from commercial use, rework allowed. I have personally used creative commons many times to find music to put in videos and images to edit in photoshop. Creative Commons also allows the user to search based on specific licenses so that you know for sure what you are legally allowed to do with the song, image, or video. 
I personally would only license some of my work with creative commons with like pictures I have taken, but as for videos, I would not.

**Comment by NickyV1234** [comment]
One of the main problems with copyright infringement that I have seen is that there are some youtubers who are getting copyright striked for extremely miniscule details that technically constitute as grounds for copy right infringement. One time a youtuber that I enjoyed watching was at risk of getting his video taken down because a car passed by playing copyrighted music and that sound was captured on the video. A grey area about copy right infringement is whether it covers situations like these, although the video was monetized the music that was played very briefly was on the video. so would that constitute as the youtuber making money off of the video using the music? In my opinion it really shouldnt.

**Comment by am0eba-byte** [comment]
**What issues have you personally seen with remediation and fair use?**
- I've never been busted on remediating others' work in my own work, but I've read tons of stories about popular artists getting slammed by lawsuits (e.g. Led Zeppelin) in areas where the "copyright infringement" issue is focused simply on similar chord structure usage in a song. Using my Led Zeppelin example, they got slammed on quite a few songs where people were trying to claim copyright in areas of their songs where the song is just barely similar to the song belonging to the artist that was suing them. I think mostly that had to do with how popular Led Zeppelin became, and how huge so many of their songs got - and I think, anytime you have work that gets really popular, people are going to try to find any possible way to suck some money out of you. 
    **What "grey areas" can make copyright infringement unclear?**
- Some grey areas I can think of is stuff like the Led Zeppelin copyright issue, where even having similar chord structures (which, in their case, had really nothing to do with how similar the actual song sounded overall to the proclaimed copyrighted song) can get people in trouble. On the same note, (*ba dum tss*) if you spend 5 minutes listening to lo-fi beat making artists on Soundcloud, literally all of the samples that they use to make their beats come directly from other songs and recordings. Yet, since those songs tend not to get very popular, those artists don't get the boot for copyright. 
    **What is Creative Commons about? Would you license your own work using Creative Commons? Why / why not?**
- Creative commons allows creators to create a unified logo clearly stating the "do's and dont's" of their work, which is easily readable and sharable with other creators to allow clear communication on what others can do with their work. It makes it easier for others to know exactly what they can't do when working with something you've created. I will certainly license my own work using Creative Commons in the future, because I love clear, easy, and concise communication of all forms - and it's such an easy way to convey your wishes clearly and effectively with other creators.

**Comment by hjl5363** [comment]
There are numerous things that come up with copyright infringement and "gray" areas. A big area that I believe is an issue that constantly comes up due to the lack of education is using/ taking photos off of websites without proper citations or credits. Bottom line, people need to learn the boundaries of the digital world when they are in grade school. Plagiarism and copying someone's English paper if often talked about, but not all aspects of plagiarism and copyright infringement are.

I see this on my own as I run my own photography business. I oftentimes see that people take photos off of my Facebook page without giving me any credit for all of my hard work. This was specifically an issue when I was in high school. In high school, I took photos of sporting events, fine arts, general school events. There would be plenty of times where I would see my photos on Instagram or Facebook with absolutely no tagging at all.

I think another reason that copyright infringement is unclear is the instant ability to take things from imaging sites, such as Google Images. With Google Images, they caution users that the image may be subject to copyright, but I have never been denied permission to download an image.

**Comment by jzm6677** [comment]
It's weird because a lot of it grey especial when it comes to fair use because even if it is only used to certain degree you can still get copyrighted. Even if unintentionally or unrealed for instance in stories a lot for creators have similar ideas and just something that happens but often people with still be copyrighted for and idea that somewhat similar to someone else. That is one of the many reasons why copyright is so sticky with creativity.

**Comment by pxl5083** [comment]
- I definetly think that remidiation and fair use is a slippery slope because you can never really tell if the person using the content is doing it for malicious purposes or doing it for the sake of a fandom or the sake of enjoying the originally published content. A good example of this can actually be seen recently in a Nintendo game called, "Super Smash Bros' Melee". It is a game that has been released for a while, and there is still a big competitive scene for it. Recently, there was a client released for the game so the players could play the game with less input lag then before, so they were able to play the game with more fluidity. Nintendo recently shut down any tournmaments using the client because it was a client using their game, all the while causing no harm to Nintendo at all and promoting their game to bigger audiences.
- The grey areas are pentiful because in a lot of cases literally nothing is set in stone with and exceptions are made all of the time, which relates to my previous point of having very little room to understand these limitations in the first place. Like an idea can be fairly similar to someone elses without copying the idea itself, people will inherently have ideas that are the same/close to each other in likliness, so I believe there does need to be a certain amount of reform to prevent falce accusations of copyright.
- I think creative commons has an amazing premise, the ability to build a brand and then be able to make it clear to other people starting out in the field what can and can not be used for influence in their brand is an amazing tool. When I start my carrer/producing content I absolutly plan on utilizing their services.

**Comment by gabbiedoster** [comment]
There are plenty of ways the "grey areas" in copyright infringement are unclear because there are so many small details you need to be aware of. With copyright, you need to understand doing the "little" things can go as far as getting you into deep water. I've worked on multiple projects where finding music for my videos was tricky. Posting to via YouTube can be difficult but, when knowing your rights and following restrictions, this will be most beneficial to any creator. The most common "gray area" of copyright infringement would be that your "own idea" is always going to be someone else's "own idea". The best thing to do is stick to your own unique way of creating and always make sure to stay informed and educate yourself while doing it!
