### ISSUE TITLE
Voyant Tools Intro Exercise

### ISSUE THREAD

**Issue by ebeshero** [newtfire/introDH-Hub#31]
Experiment with [Voyant Tools](https://voyant-tools.org/) on any text you wish, perhaps readings from our class, or from sites of interest to you. 
* Tell us about the text you surveyed in Voyant Tools (and/or provide a link)
* Post an image taken of Voyant's rendering of your text here in this thread, and see if you can include some website embed code with your post.
* Comment to reflect a little on what you're seeing in the Voyant Tools view: What can you see about your text that seems interesting? Do you see anything about the patterns of word use that surprises you? Or does the view confirm something you expected to see?

**Comment by nmiano** [comment]
The Text I surveyed was the illustration "Percy Jackson and The Lightning Thief" by Rick Riordan

https://voyant-tools.org/?corpus=543c5ea4822a178b51c174426d9ae70c

Comment: What's interesting about the text is that it didn't reveal as much words regarding the Greek gods than I expected. What also surprised me was that "Grover" was mentioned more than "Annabeth."  I really expected to see "said" to be the biggest word in this text because it's a very conversation driven text.

**Comment by nmiano** [comment]
@ebeshero Here' the book link itself: https://getfreestories.weebly.com/uploads/7/9/0/2/79020522/lightning_thief_the__percy_jac_-_rick_riordan.pdf

**Comment by ebeshero** [comment]
@nmiano See if you can take a screen capture and save locally and then see if you can insert the image in your comment! I think that's what we did last fall.

**Comment by jbg5721** [comment]
Link to my surveyed website: https://climate.nasa.gov/effects/ 
I chose this site just because it is a topic I am interested in.

Comment: What I find interesting is about this graph is that there are not many "common words." I expected to see at least a few common words, such as: 'the.' I am not surprised to see climate, change, heat, sea, ice, heat, all over the place

<img width="421" alt="VoyantSS_JG" src="https://user-images.githubusercontent.com/78062156/109750116-d77e4c00-7ba9-11eb-8a85-48160c14df35.png">

**Comment by amayadwillis** [comment]
I used the text from The Scarlet Letter, I found it on The Project Gutenberg website here: 
https://www.gutenberg.org/files/25344/25344-h/25344-h.htm
![Capture1](https://user-images.githubusercontent.com/70728138/109857141-5ade8280-7c28-11eb-8d57-4dc9bbbecf39.PNG)
![Capture](https://user-images.githubusercontent.com/70728138/109857145-5b771900-7c28-11eb-93f0-eb0ac3dae660.PNG)

The main thing I was interested in looking at for this book was the most used words. I was a little surprised to see that "letter" and "scarlet" weren't even in the top ten. The top five most used words are "Hester," "Little," "Pearl," "Old," and "Child." I think it goes to show that although the story is called "The Scarlet Letter" the book isn't about Hester's shame and punishment, its actually about her and her love for her child.

**Comment by ras6164** [comment]
I analyzed a research article on Facebook advertising which can be read here: http://designdamage.com/wp-content/uploads/2009/04/Understanding-the-Value-of-a-Social-Media-Impression.pdf.

![download (2)](https://user-images.githubusercontent.com/78106949/109861083-ebb75d00-7c2c-11eb-85f8-a8749d06b096.png)

For most of the words, I expected to see them as some of the top words used in the text (impressions, ad, organic, etc). However, I was shocked to see homepage and exposed as while I remember some of that in the reading, it was not a key takeaway that stuck with me afterwards. In addition to this, I found it interesting that social was used a lot more often than media. I would have thought that those words would not have such a wide range of use as it is a phrase that is commonly used together in the text.

**Comment by erinmooney** [comment]
I used Plant Lore, Legends, and Lyrics by Richard Folkard from Project Gutenberg. (https://www.gutenberg.org/ebooks/44638)
 The outcome was :
<img width="311" alt="PlantLoreWordBubble" src="https://user-images.githubusercontent.com/78123905/109868428-96337e00-7c35-11eb-9986-13992f0f827c.PNG">

For text about Plant Lore, the Word Bubble words are about what I expected! "Called" was a bit of a surprise, but I guess it makes sense because the text needs to identify different plants. "According" was also not expected, but from this word I can extrapolate that this text is more like a historical viewpoint of lore instead of a cultural one. Like, instead of telling the story of the plant, it is more like, "according to sources, this plant..." I really like this Bubble, and how the words really suit their source!

**Comment by kjc6167** [comment]
I chose an article on NASA's Perseverance Mars rover. (https://mars.nasa.gov/news/8875/testing-proves-its-worth-with-successful-mars-parachute-deployment/)

![image](https://user-images.githubusercontent.com/78039750/109872674-bca7e800-7c3a-11eb-8e0c-c39fc42544d5.png)
![image](https://user-images.githubusercontent.com/78039750/109872747-d812f300-7c3a-11eb-9513-4c5c03b330bd.png)

I thought it was interesting to look at which words were most commonly used throughout the article. Since the title was "Testing Proves Its Worth With Successful Mars Parachute Deployment," I assumed that "testing", "Mars", and "parachute" would be the most common words. Although "Mars" was the most used word, "rover", "perseverance", and "mission" were used much more than the previously mentioned list. However, I was not surprised that these words were very common in this article.

**Comment by chrisklein10** [comment]
Link to surveyed website: https://liveforlivemusic.com/news/john-lennon-gimme-some-truth-deluxe-box-set/

Something interesting to me is the words of social media on here because to think he died a way long time before social media is a thing and that he is still so relevant that there is an account under his name is amazing.
Patterns of the words don't really surprise me except there is one word, which is jazz that shocks me a bit.
 
![Screenshot (58)](https://user-images.githubusercontent.com/78046640/109877398-f8de4700-7c40-11eb-8a87-17822bfe7f87.png)

**Comment by Jakeruff29** [comment]
I read a biography on Dale Earnhardt, one of NASCARs best drivers.  
![download](https://user-images.githubusercontent.com/78121863/109879107-275d2180-7c43-11eb-901d-48ba7c4b8d4d.png)
Something interesting I found is that even if you had no idea who Dale Earnhardt was, you would be able to gather much information just from the words shown; such that "championship" or "championships" were displayed 17 times, and the word "win" was displayed 9 times.  Something else interesting that I had found was that "Dale" was referred to 14 times and "Earnhardt" was referred to 26 times, almost double.  Also interesting is that "Sr." or "senior" did not make the commonly used words list even though Dale Earnhardt can refer to Dale Earnhardt Jr. as well.

**Comment by luh429** [comment]
I used the Lorax as my text. Here is the link to the pdf I used: [http://dep.wv.gov/WWE/Programs/nonptsource/Documents/TheLorax.pdf](http://dep.wv.gov/WWE/Programs/nonptsource/Documents/TheLorax.pdf)
I wasn't very surprised that words like Lorax, trees, and truffula were some of the most common words. However I found it odd that the word "ler" as in "Once-ler" was used quite frequently but the word "once" wasn't even in the top 55 words. I also thought it was comical that most of the most common words were made up words. For example Lorax, truffula, ler, thneed, biggering, and biggered. 
![Lorax](https://user-images.githubusercontent.com/78118867/109897283-7a919d00-7c60-11eb-83d6-b6d40affd46c.PNG)

**Comment by ebeshero** [comment]
@luh429 That's an interesting discovery you've made! I think Once- and -ler got cut in half by the - (hyphen) in between them. I wonder if Voyant is keeping only the second half of a hyphenated word?

**Comment by Awebster7** [comment]
- The article I picked was titled "For Travel, a Sustainable Comeback?" from The New York Times! I simply just picked this article because it looked interesting. Link: [https://www.nytimes.com/2021/02/25/travel/sustainable-travel-environment-pandemic.html](url)

<img width="400" alt="Screen Shot 2021-03-03 at 10 54 16 PM" src="https://user-images.githubusercontent.com/78045055/109909081-7a4ecd00-7c73-11eb-8d58-22a98a88e9a2.png">

- I found it interesting how unaware I was while reading this article. The results of the graph made me more aware of what I didn't pick up on when just reading the article once. I was surprised to see carbon as the second most common word used in the article because I don't remember reading that word frequently. Lastly, it was obvious to me that travel was the biggest word because it was an article on travel.

**Comment by debbie-evans** [comment]
After trying to think of something serious to look at over the past day or so, I decided to put the Bee Movie script into Voyant (https://web.njit.edu/~cm395/theBeeMovieScript/) 

![Bee Movie](https://user-images.githubusercontent.com/78060074/109981030-81ef8f80-7cce-11eb-8039-6842b77f5055.png)

I can't say that anything in the word frequency really surprised me, the top words that aren't ones that are commonly used in dialogue (I'm, it's, just, etc.) were exactly what I expected (bee, bees, honey, etc.). One thing that I did find interesting is that the word "thinking" appears in the script twenty-seven times, but the reason that number is so high is because the phrase "thinking bee" is used eleven times in quick succession.

**Comment by aidanvray** [comment]
I decided to analyze Donald Trump's most recent speech from this year's CPAC convention. I got the transcript from [https://www.rev.com/blog/transcripts/donald-trump-cpac-2021-speech-transcript](url). 

![trump](https://user-images.githubusercontent.com/78158447/109985912-3be8fa80-7cd3-11eb-83d8-fd8bc25d144c.JPG)

Due to the way the transcript was formatted, it stated Trump's name along with timestamps above every line he said. That's why his first and last name are the most repeated things from the transcript. It's also why "01" was repeated a few times. Aside from that a lot of phrases related to his most recent talking points were repeated a fair amount. Some of these include election, won, Biden, China, and Democrats. The only thing that really surprised me was that rigged and fraud were barely used in the speech.

**Comment by WillStill** [comment]
I used the text  from a short story called _Safari_ by Jennifer Egan. https://www.newyorker.com/magazine/2010/01/11/safari-3
![TheSafariVoyantTools](https://user-images.githubusercontent.com/78114286/109989368-6f795400-7cd6-11eb-9395-c59b506c6895.PNG)
I noticed that the names of characters were the most prevalent, which should be expected. The next most prevalent words were names of relationships between the characters. "father," "children," and "group," are the few that show. After that, a lot of the words found were of no significant importance. Some of the most prevalent words were "it's," "she'll," "like," "he's," and "she's."

**Comment by thammer12499** [comment]
![index](https://user-images.githubusercontent.com/78119613/109992576-65a52000-7cd9-11eb-878b-68f2470b51d9.png)
The subject of the doc was a research paper into the effects of blue light on the human eye and its potential effects on the brain. I'm not surprised by some of the words to come up so frequently but rather I'm surprised by the number of filler words used frequently within the document. It's not something I often notice even reading aloud.

**Comment by SoulEpicness** [comment]
I Decided to look at speed runs and wanted to look at a guide for Dark Souls.
Link: [Dark Souls speedrunning](https://wiki.speedsouls.com/darksouls:Getting_Started)
![Dark Souls words](https://user-images.githubusercontent.com/78154419/109992640-748bd280-7cd9-11eb-8495-0fb7341aadf7.png)

I thought that in the text I would see more terms that were based on movement tactics and shortcuts. I instead saw Dark, Souls, and speedsouls more than I thought I would have, but after seeing them I saw words I thought I  might see such as stamina, menuing, and route.

**Comment by TOMZS1** [comment]
The text that I used is from "Alice in Wonderland", by Lewis Carrol. This is one of my favorite books and I thought it would be interesting to see the most frequent words in this book.

[Alice in Wonderland](http://www.gutenberg.org/files/11/11-h/11-h.htm)

![Alice in Wonderland](https://user-images.githubusercontent.com/78178588/109995793-9aff3d00-7cdc-11eb-97ab-f6ae2cac5333.png)

I like how you can tell what the story's about. Its like the main things that people know about the story are the top words used in this book.

**Comment by Tonya-Velcko** [comment]
The text I used was Shakespeare's Macbeth from this link: http://shakespeare.mit.edu/macbeth/full.html
![voyant image](https://user-images.githubusercontent.com/78163832/111090670-ea2c4580-8506-11eb-9522-3742d1616f35.png)
I expected the characters' names to be common, but there were some words that were a surprise, like witch, sleep, and exeunt.
