### ISSUE TITLE
Remediation, Remixing, and Copyright Readings / Discussion

### ISSUE THREAD

**Issue by ebeshero** [newtfire/introDH-Hub#33]
Read the two following short articles:
<ul>
                        <li><q><a href="https://www.wipo.int/wipo_magazine/en/2015/03/article_0006.html">Remix Culture and Amateur Creativity: A Copyright Dilemma</a></q></li>
                        <li><q><a href="https://fairuse.stanford.edu/overview/fair-use/four-factors/">Measuring Fair Use: The Four Factors</a></q></li>
                     </ul>

Then respond:
* Highlight a passage from either article that surprised you about copyright infringement and "fair use": What surprised you? 
* Identify one or two "grey areas" identified in the readings that can make copyright infringement unclear.

**Comment by erinmooney** [comment]
" A violation of copyright?
Many within the cultural industries believe that any unauthorized extract taken from a pre-existing work constitutes copyright infringement. Strictly speaking, they are right. Remixes do violate the copyright in a pre-existing work, insofar as the act of creating a second work that contains elements of an original work violates both the right of reproduction (Article 9 of the Berne Convention) and the right of communication to the public (Article 8 of the WIPO Copyright Treaty) of the original author. "

So, according to this Fanfiction and Fanart is illegal because it infringes on the original authors copyright / intellectual property. When I had to study copyright law, we zoned in on Disney because they are the most active about their copyright. If you look into the legal content for Disney, you'll see how they dodge and use these laws to their advantage. There are other companies that respond to violations, but Disney is just the biggest example.

**Comment by Tonya-Velcko** [comment]
"Remixes do violate the copyright in a pre-existing work, insofar as the act of creating a second work that contains elements of an original work violates both the right of reproduction (Article 9 of the Berne Convention) and the right of communication to the public (Article 8 of the WIPO Copyright Treaty) of the original author."

I found this surprising because there are so many remixes out there, from music to film parodies, to, like Erin discussed, fanfiction and fanart. There are multiple sites that serve as platforms for these works, encouraging it, and it is strange to think that all of that is technically illegal, and thus, these sites illegal...

**Comment by thammer12499** [comment]
"The moral rights of the original author also come into play. Under Article 6bis of the Berne Convention, “the author shall have the right to claim authorship of the work and to object to any distortion, mutilation or other modification […] which would be prejudicial to his honor or reputation”. When a given song is remixed in a way that strongly decontextualizes its meaning, the author of the original work can claim a violation of moral rights."

"In other words, just because images from a cinematographic work are mixed with a specific song that does not mean that the public will stop purchasing either the original movie or the original soundtrack. On the contrary, such remixes or mash-ups may constitute free publicity for the pre-existing work."

These seem strongly contradictory.

**Comment by nmiano** [comment]
"The moral rights of the original author also come into play. Under Article 6bis of the Berne Convention, “the author shall have the right to claim authorship of the work and to object to any distortion, mutilation or other modification […] which would be prejudicial to his honor or reputation”. When a given song is remixed in a way that strongly decontextualizes its meaning, the author of the original work can claim a violation of moral rights."

This section of the passage from "Remix Culture and Amateur Creativity: A Copyright Dilemma" was surprising to me because it essentially allows creators of music to have power to say which versions of his/her song are crap or not, I thought that was quite funny! In all seriousness though, I think that this power to the creator is a good power to possess and it gives you almost something like a safety blanket.

**Comment by nmiano** [comment]
hah @thammer12499 we did the same section

**Comment by ras6164** [comment]
"Existing copyright laws do not adequately address the challenges arising from the wealth of amateur creativity facilitated by the tools available within the digital environment."

Why would legislative changes not be made when the environment in which copyright applies has completely changed over the past several years? Nations that fail to protect IP/copyright infringement from occurring can often lead to a magnitude of problems including distrust from foreign investors and encouraging piracy and counterfeiting. 


"Many within the cultural industries believe that any unauthorized extract taken from a pre-existing work constitutes copyright infringement. Strictly speaking, they are right."
vs. 
"However, it could also be argued that remixes and mash-ups are compliant with copyright law. For example, Article 13 of the Agreement on Trade-Related Aspects of Intellectual Property (TRIPS) states that in 'certain special cases which do not conflict with a normal exploitation of the work and do not unreasonably prejudice the legitimate interests of the right holder'"

A common grey area identified in the articles is whether or not a remix still infringes on the original creator's copyright protections or whether they can be legally created under amateur creativity clause. On one hand, certain pieces of legislation can be referenced to support the idea remixes violate copyright law, but one can also cite legislation that permits remixes.

**Comment by ebeshero** [comment]
@Tonya-Velcko @erinmooney More like *potentially* illegal (or infringement) if a court decides it that way...

**Comment by jbg5721** [comment]
"One might also argue that remix works are akin to quotations protected under Article 10 of the Berne Convention. Under this Article, it “shall be permissible to make quotations from a work which has already been lawfully made available to the public, provided that their making is compatible with fair practice, and their extent does not exceed that justified by the purpose”. While quotations are often associated with literary works, the Berne Convention refers to “quotations from a work”, which may include audiovisual, musical or even photographic works. In 2011 the Court of Justice of the European Union decided in Eva-Maria Painer v. Standard Verlags GmbH and others (CJEU-C/145/10) that photography could be quoted, as long as it had been made lawfully available to the public and the name of the author was indicated. It could therefore be argued that remixing audiovisual or musical works is similar to quoting from a literary work."

I was surprised that photography was mentioned in this. I often see that photographers don't want their work being used by others regardless. One thing that I personally get confused with is, "as long as it had been made lawfully available to the public." What would be lawfully available? or not available.

**Comment by thammer12499** [comment]
> 
> 
> hah @thammer12499 we did the same section

Oh I hadn't even noticed, lol.

**Comment by nmiano** [comment]
Grey Area 1:
"The situation, however, remains less than clear elsewhere. In the United States, the courts are still grappling with the issue, as indicated in Stephanie Lenz v. Universal Music Corporation which has been ongoing since 2007. The claimant, Stephanie Lenz, posted a video to YouTube of her children dancing and running around in her kitchen with Prince’s Let’s Go Crazy playing in the background. A few months later, Universal Music Corporation had the video removed from YouTube claiming copyright infringement; an allegation strongly contested by Ms. Lenz."

The grey area is what is considered an accident or what's considered a blatant act of infringement in a YouTube video, I watch YouTube a lot and I notice that this is a common problem with videos being taken down. Someone accidentally plays a song from a playlist that is copyrighted. He/She shouldn't get a strike but she does anyways just because its a copyrighted song. Where is that boundary of infringement on YouTube?

**Comment by kjc6167** [comment]
_Remix Culture and Amateur Creativity: A Copyright Dilemma_
"The moral rights of the original author also come into play. Under Article 6bis of the Berne Convention, “the author shall have the right to claim authorship of the work and to object to any distortion, mutilation or other modification […] which would be prejudicial to his honor or reputation”. When a given song is remixed in a way that strongly decontextualizes its meaning, the author of the original work can claim a violation of moral rights."

I never knew that copyright infringement also implied the violation of an artist's moral rights. I guess I never saw art as a type of moral medium that reflects the creator.

_Measuring Fair Use: The Four Factors_
"Determining what is transformative—and the degree of transformation—is often challenging. For example, the creation of a Harry Potter encyclopedia was determined to be “slightly transformative” (because it made the Harry Potter terms and lexicons available in one volume), but this transformative quality was not enough to justify a fair use defense in light of the extensive verbatim use of text from the Harry Potter books."

I found this paragraph to be a "gray area" because it shows how determining if a work is transformative enough to be infringing on a copyright is difficult and varies from case to case. It makes you wonder if there are some pieces that purposefully infringe copyrights but do so with a degree of transformation that make it barely legal.

**Comment by ebeshero** [comment]
Example of a case resolved amicably (in a friendly deal-making way): https://www.pon.harvard.edu/daily/dealmaking-daily/in-dealmaking-with-tom-petty-sam-smith-backs-down/

**Comment by debbie-evans** [comment]
"For example, in one case an artist used a copyrighted photograph without permission as the basis for wood sculptures, copying all elements of the photo. The artist earned several hundred thousand dollars selling the sculptures. When the photographer sued, the artist claimed his sculptures were a fair use because the photographer would never have considered making sculptures. The court disagreed, stating that it did not matter whether the photographer had considered making sculptures; what mattered was that a potential market for sculptures of the photograph existed. (Rogers v. Koons, 960 F.2d 301 (2d Cir. 1992).)"

I find this case to be very interesting, because if the sculptor had sculpted whatever was depicted in the photograph, this never would have been an issue. How did the photographer get a copyright on the photo? Did they own whatever was depicted? If not, could the owner of whatever was in the photograph sue the photographer? It's just a messy situation.

**Comment by amayadwillis** [comment]
"A disclaimer is a statement that “disassociates” your work from the work that you have borrowed. For example, if you write an unauthorized biography of Mickey Mouse, you may include a disclaimer such as, “This book is not associated with or endorsed by the Walt Disney Company.” Will it help your position if you use a disclaimer? In close cases where the court is having a difficult time making a fair use determination, a prominently placed disclaimer may have a positive effect on the way the court perceives your use. However, generally a disclaimer by itself will not help. That is, if the fair use factors weigh against you, the disclaimer won’t make any difference."

This section seems to be saying mostly that disclaimers don't help, which was a little surprising to me. It also says "if the fair use factors weigh against you..." which leads to the idea that there may be situations where a disclaimer might help? 

"In some cases, the amount of material copied is so small (or “de minimis”) that the court permits it without even conducting a fair use analysis....As with fair use, there is no bright line test for determining a de minimis use."

This section is another confusing part, because how do they determine what is small enough of an infringement for them to allow? Does allowing small infringements encourage it to happen repeatedly since there are no consequences for doing it?

**Comment by Jakeruff29** [comment]
"The moral rights of the original author also come into play. Under Article 6bis of the Berne Convention, “the author shall have the right to claim authorship of the work and to object to any distortion, mutilation or other modification […] which would be prejudicial to his honor or reputation”. When a given song is remixed in a way that strongly decontextualizes its meaning, the author of the original work can claim a violation of moral rights."

I found this interesting because the author can not only claim copyright on a remix of a song, which is a very popular thing in todays music, but they can also claim copyright even if the song was "Strongly Decontextualized" meaning they took parts of the song out of context.  Does that mean that copyright can be claimed if someone who wrote a song used a similar line as another song,  The author of the song that was released first could claim copyright even if the other author had never heard it?

**Comment by WillStill** [comment]
"When a given song is remixed in a way that strongly decontextualizes its meaning, the author of the original work can claim a violation of moral rights."

I found this interesting. In the past few years, I have seen a larger influx of remixes posted to YouTube intended to be crude jokes. They haven't been taken down on the site, but under legal grounds they could be.
Though, this becomes a grey area under Article 10 of the Berne Convention. It “shall be permissible to make quotations from a work which has already been lawfully made available to the public, provided that their making is compatible with fair practice, and their extent does not exceed that justified by the purpose”.

**Comment by ebeshero** [comment]
Collecting some excellent questions being raised here: 
* How did the photographer get a copyright on the photo?  (thanks @debbie-evans )
* '"One thing that I personally get confused with is, "as long as it had been made lawfully available to the public." What would be lawfully available? or not available."' (thanks @jbg5721 )
* How small is small enough to count as "fair use" in the US law? 
* (my distillation of several posts): Are we seeing tension between the international Berne convention and US lawcourts on remixing culture?

**Comment by Tonya-Velcko** [comment]
"Determining what is transformative—and the degree of transformation—is often challenging. For example, the creation of a Harry Potter encyclopedia was determined to be “slightly transformative” (because it made the Harry Potter terms and lexicons available in one volume), but this transformative quality was not enough to justify a fair use defense in light of the extensive verbatim use of text from the Harry Potter books. (Warner Bros. Entertainment, Inc. v. RDR Books, 575 F.Supp.2d 513 (S.D. N.Y. 2008).)"

What? How could a **Harry Potter** Encyclopedia not have quotes from the books? It's about the Harry Potter world! How can they say that the fair use is transformative because of the definitions of terms, while also saying it is infringement for the same reasons?

**Comment by TOMZS1** [comment]
"YouTube’s Content ID software analyzes samples of musical works provided by the recording industry and collective management organizations and compares them with the videos uploaded to the website. The software establishes a link between an existing work and an uploaded work such as a remix. If the content matches, the video may be automatically blocked or the sound muted and the user is automatically informed by e-mail that the material has been disabled “as a result of a third-party notification claiming that this material is infringing”.(WIPO, Rostama)."

How can the software tell that the users videos is infringing, does it take each content and compare it to each other, also what determines the user content is good enough to be consider a remix, and what if the new remixed content takes viewership from the original work?

**Comment by nmiano** [comment]
Gray Area 2 ("Measuring Fair Use: The Four Factors"): "Some people mistakenly believe it’s permissible to use a work (or portion of it) if an acknowledgment is provided." 

This short passage is a grey area because, again like the last one, there is a line that has to be drawn somewhere but there is always a case where we don't know if the line was passed or not. It is very hard to determine where permission may be granted to pass.

**Comment by Awebster7** [comment]
**Highlight a passage from either article that surprised you about copyright infringement and "fair use": What surprised you?**
"Stephanie Lenz, posted a video to YouTube of her children dancing and running around in her kitchen with Prince’s Let’s Go Crazy playing in the background. A few months later, Universal Music Corporation had the video removed from YouTube claiming copyright infringement; an allegation strongly contested by Ms. Lenz." 

The copyright claims that YouTube makes have always surprised me. I watch YouTube and I notice that a lot of YouTubers are always careful not to have music playing in the background because they don't want to get copyrighted. I understand that people profit and make a living off of YouTube but so do other people on platforms like Instagram and Tik Tok. Music is played on Instagram and Tik Tok without copyright claims. The YouTube strict copyright rules on music in the background of videos has always surprised me.

**Identify one or two "grey areas" identified in the readings that can make copyright infringement unclear.**

"When you review fair use cases, you may find that they sometimes contradict one another or conflict with the rules expressed in this chapter. Fair use involves subjective judgments, often affected by factors such as a judge or jury’s personal sense of right or wrong. Despite the fact that the Supreme Court has indicated that offensiveness is not a fair use factor, you should be aware that a morally offended judge or jury may rationalize its decision against fair use."

This seems like a grey area because it is based on others and if they deem it wrong. It seems that depending on who you are dealing with, things could end differently, which makes things unclear and hard to understand.

**Comment by luh429** [comment]
"YouTube’s Content ID software analyzes samples of musical works provided by the recording industry and collective management organizations and compares them with the videos uploaded to the website. The software establishes a link between an existing work and an uploaded work such as a remix. If the content matches, the video may be automatically blocked or the sound muted..."
This is interesting that YouTube has a software that can analyze weather or not something is copyright. With there being a lot of gray space when it comes to copyright it doesn't seem like a computer would be able to accurately tell the difference between something that is a copyright violation and a remix. Then it takes it down automatically on its own without any actual people involved in the decision.

"The situation, however, remains less than clear elsewhere. In the United States, the courts are still grappling with the issue, as indicated in Stephanie Lenz v. Universal Music Corporation which has been ongoing since 2007. The claimant, Stephanie Lenz, posted a video to YouTube of her children dancing and running around in her kitchen with Prince’s Let’s Go Crazy playing in the background. A few months later, Universal Music Corporation had the video removed from YouTube claiming copyright infringement; an allegation strongly contested by Ms. Lenz."
This is a grey area because Ms. Lenz could argue the content of the video wasn't intentionally supposed to be the song in the background, but instead the children playing. But then someone may copy music and just put a video up with it and claim their intent was to show a video not copy the music. When in reality the video could just be a scapegoat to be able to share the music as their own.
