### ISSUE TITLE
Mystery Text Discussion of wc.txt

### ISSUE THREAD

**Issue by ebeshero** [newtfire/introDH-Hub#44]
Post your ideas and findings and screen captures about wc.txt here!

**Comment by IsabelCriswell** [comment]
<img width="1440" alt="Screen Shot 2021-10-11 at 6 10 17 PM" src="https://user-images.githubusercontent.com/89947104/136864971-5a6aee60-5cee-45eb-a58a-e465cf3dc7b5.png">
<img width="1440" alt="Screen Shot 2021-10-11 at 6 16 45 PM" src="https://user-images.githubusercontent.com/89947104/136864972-cd289739-525e-466d-b4fd-44657251bf41.png">

I found it interesting that Heathcliff occurred more often than Catherine, but also I've never read Wuthering Heights, so my analysis should be taken with a grain of salt since it is out of context.

**Comment by jmp7651** [comment]
When I was exploring the wc text, it was an unknown story to me and I did not know the source material. However, with the usage of the corpus analysis tools, I was able to get an idea of the plot. When I put the text through AntConc, from the various set of clusters, the one that stuck out to me was the two gram combination, "I was". This made me assume that this story was a retelling of events to provide context behind a major plot point in the story. Clicking on the concordance, my assumptions were correct, as some of the context behind the clusters involve events that occur at different times, from times ranging from September to Christmas. The frequency of Catherine from the context within the concordance also make me assume that she is someone dear to the narrator and the events that transpire in the retelling possibly occur because an of event befalling on her.


![image](https://user-images.githubusercontent.com/89952683/136881812-86eecccd-244b-48ef-bce8-9657950e8b9d.png)
![image](https://user-images.githubusercontent.com/89952683/136883336-a59b89ac-1c23-4545-8c89-bcc3eef1ea6b.png)

**Comment by als7294** [comment]
I am going to take a guess that this is a horror script about a girl named cathrine and her brother
<img width="588" alt="antcomp" src="https://user-images.githubusercontent.com/89995047/137010643-6c1e742c-c63e-43f8-814a-779b24e39f6a.png">

After reviewing the data from voyant tools however, I can say that I now believe the text to feature someone involving "linton" as the climax, as it peaks heavily.

<img width="1280" alt="voyant tools" src="https://user-images.githubusercontent.com/89995047/137011265-e6002148-707a-4575-a342-904640086806.png">
