### ISSUE TITLE
Mystery Text Discussion of lr.txt

### ISSUE THREAD

**Issue by ebeshero** [newtfire/introDH-Hub#45]
Post your ideas and findings and screen captures about lr.txt here!

**Comment by austinmurry** [comment]
So when I started exploring the lr text, I really wasn't sure of what it was. When I put the text through antconc, the set of clusters that stuck out to me was two words, "the ring". This started to give me a bit of an inkling about what it might be, so I clicked on it to see the concordance and my suspicions were proven correct as phrases came up involving two major people, Gandalf and Gollum. This text is either a pull from the Lord of the Rings, or the Hobbit series. The thing that solidified what this text was is when I put it through Voyant and one of the biggest words in my scramble is Frodo. This text is most certainly the Lord of the Rings book, so I will include images of some of my findings.

<img width="786" alt="Screen Shot 2021-10-11 at 11 26 51 AM" src="https://user-images.githubusercontent.com/77990010/136817295-9d180e29-87ea-4f25-bc72-9fc4e6ea2085.png">
<img width="787" alt="Screen Shot 2021-10-11 at 11 28 57 AM" src="https://user-images.githubusercontent.com/77990010/136817326-0bdc60ae-7e77-48e2-a360-cb2e1e52ce35.png">
<img width="1680" alt="Screen Shot 2021-10-11 at 11 23 31 AM" src="https://user-images.githubusercontent.com/77990010/136817363-ee1a06be-5282-4582-80ec-664512d64e3d.png">

**Comment by julianjmg** [comment]
When I first started out with the lr.txt file, I had no idea what it could be, so I first started out with Ngrams starting with a size of 3 and one of the first things that stood out to me was the word shire. I didn't know what a shire was, so I looked it up and found out that it is a type of county in England. So that narrowed down the setting quite well. I scrolled a bit further down in the N-gram size of three and i found "in the dark", and "the light of". These are pretty contrasting ideas and they had a similar frequency throughout the text. This alluded to a "good vs evil" conflict which had narrowed down my thoughts even further. I then looked at single n-grams and once i scrolled past all of the articles, prepositions, pronouns, and etc, I found the character Gandolf which is a main character in the story of Lord of the Rings.
<img width="296" alt="Screen Shot 2021-10-11 at 3 00 51 PM" src="https://user-images.githubusercontent.com/89925936/136847350-d607841d-3c3b-443d-84fb-13747aa13d76.png">
<img width="233" alt="Screen Shot 2021-10-11 at 3 02 58 PM" src="https://user-images.githubusercontent.com/89925936/136847352-34f31fdf-783b-4f5c-86b1-fc33c038d397.png">
<img width="213" alt="Screen Shot 2021-10-11 at 3 03 17 PM" src="https://user-images.githubusercontent.com/89925936/136847353-83a5b4e4-367f-4444-9e46-e7e9c8257732.png">
<img width="251" alt="Screen Shot 2021-10-11 at 3 03 50 PM" src="https://user-images.githubusercontent.com/89925936/136847354-c630c277-6bfd-46a1-a42c-4ef817b47ace.png">

**Comment by SCD5363** [comment]
![AntConSamDeeter_001](https://user-images.githubusercontent.com/89928602/137015412-9324f466-c312-43c1-9ecd-216f9eee3a09.PNG)
Ir.txt I found this "it is" phrase interesting because it could be replaced by it's but the author chose not to. Also the amount of time they use "it is" is a crazy amount. 
![LrVoyant](https://user-images.githubusercontent.com/89928602/137015844-f7f4f18a-a50f-4830-931a-a23dbc2cc764.PNG)
Using Voyant tools really reveals more of the text and we find that this is The Lord Of the Rings

**Comment by fkb5105** [comment]
AntConc Exercise 2
 
So, basically the text I chose (without knowing beforehand) was "Lord of the Rings" and as far as I know the first book of the trilogy. Now even if you didn't read the books or know the story, using AntConc and Voyant you can tell some things about the story, like this place called "The Shire", or these creature’s hobbits, maybe even the name of some characters like Frodo, Gandalf, or Sam. Having already read the books it’s pretty interesting to see how words like Shire or Bilbo are mentioned mainly at the beginning which is when they appear the most and then throughout the story practically disappear.



<img width="1440" alt="Screen Shot 2021-10-11 at 11 16 00 PM" src="https://user-images.githubusercontent.com/90004771/137015701-ad5b08c3-d252-4030-b59a-25d301c7ce9a.png">
<img width="1440" alt="Screen Shot 2021-10-11 at 11 16 30 PM" src="https://user-images.githubusercontent.com/90004771/137015708-20b149d0-2265-4ac1-b7e3-65257174cd44.png">
<img width="1440" alt="Screen Shot 2021-10-11 at 11 18 51 PM" src="https://user-images.githubusercontent.com/90004771/137015712-cdd69d79-9131-4927-8d54-5b5a8619cfd6.png">
<img width="1440" alt="Screen Shot 2021-10-11 at 11 20 08 PM" src="https://user-images.githubusercontent.com/90004771/137015714-f0b22770-e99d-4128-984f-5d3be824b6da.png">
<img width="1440" alt="Screen Shot 2021-10-11 at 11 21 07 PM" src="https://user-images.githubusercontent.com/90004771/137015718-093775ed-ad88-45f7-9fd2-91374e99ec6e.png">

**Comment by ztd5049** [comment]
When I first opened the text document in AntConc, I immediately knew what the book was. Not specifically which book of the series, but I did know it was a part of the Lord of the Rings books. I saw hobbit, Frodo, Gandalf, and ring all in the top words on voyant, and I saw prepositional phrases like in the shire. An interesting phrase was "out of the". I found this interesting because a lot of the word in context showed a mystical or mysterious tone, which makes sense for a Lord of the Rings book.

![ConcKWIC1](https://user-images.githubusercontent.com/89958088/137247187-42d6dce7-b986-4f92-a5af-0d196cc91aac.PNG)
![ConcKWIC2](https://user-images.githubusercontent.com/89958088/137247189-d6f0206c-3f17-44c8-8175-44c06c3ff24e.PNG)
![ConcKWIC4](https://user-images.githubusercontent.com/89958088/137247191-bcd83534-1ed8-48cf-aeff-31c7096d7c7f.PNG)
