### ISSUE TITLE
Remediation, Remixing, and Copyright Readings/Discussion

### ISSUE THREAD

**Issue by ebeshero** [newtfire/introDH-Hub#47]
Read the three following short articles:
<ul>
                        <li>Guilda Rostama <q><a href="https://www.wipo.int/wipo_magazine/en/2015/03/article_0006.html">Remix Culture and Amateur Creativity: A Copyright Dilemma</a></q> *Wipo Magazine*, June 2015.</li>
                        <li>Rich Stim, <q><a href="https://fairuse.stanford.edu/overview/fair-use/four-factors/">Measuring Fair Use: The Four Factors</a></q> Stanford U. Libraries, 2019. </li>
<li>Mariah Lewis, <q><a href="https://librarynews.blog.fordham.edu/2021/02/25/fair-use-week-2021/">Fair Use in the Real World</a></q>, Fordham Library News, 2021.</li>
                     </ul>

Then respond:
* Highlight a passage from any of the articles that surprised you about copyright infringement and "fair use": What surprised you? 
* Identify one or two "grey areas" identified in the readings that can make copyright infringement unclear.

**Comment by ztd5049** [comment]
Something that suprised me:
The idea of fair use intrigued me in multiple aspects. I've explored fair use on YouTube and their Content ID system. Reading the official guidelines of fair use, it brought to my attention my own experiences with copyright. I've uploaded multiple YouTube videos of piano covers of popular songs. Some of these videos saw a copyright claims. While only restricting monetization of the videos, I believe all of my content was within fair use. Being educational, non-destructive of original content, a new form of adaptation with new visuals and insights amongst other things, it seems as though some guidelines can be ignored until disputed. 

Grey Areas:
The first gray area that I noticed was the matter of opinion

"Despite the fact that the Supreme Court has indicated that offensiveness is not a fair use factor, you should be aware that a morally offended judge or jury may rationalize its decision against fair use."
- [Stanford Libraries](https://fairuse.stanford.edu/overview/fair-use/four-factors/)

This is most likely one of many cases that were not purely determined by the guidelines. Unfortunately, I feel this is a difficult problem to fix as it is not dissimilar to the many other problems in our legal system.

Secondly in Reiner v. Nishimori Fair Use was found while other similar cases were found as not fair use. Their use of this identical image was found to be in fair use as it wouldn't infringe upon the photographers market to sell work and educational purposes. Despite being a clear unpermitted use of the photographers work, this was found to be ok. It seams that some guidelines are followed in certain cases while others are overlooked. Determining if a piece of work is educational, or provides insight can be difficult because that is mostly a subjective quality that cannot be quantified by a simple law or ruleset.

**Comment by bmg5877** [comment]
A thing that surprised me was that there was no actual limitation on how much of a work you could use and have it be "fair use". I was always told never to use more than around 15 seconds of a video clip or music or more than a couple of sentences in an essay when I was younger. Another thing I thought was interesting was how YouTube's copyright software functions. I used to have YouTube channel years back, and I sometimes would get my videos copyright claimed even though I was using royalty-free music and even citing my sources when needed. 

A grey area that was discussed was the "fifth" factor, which discussed how some judges go off of their own morality during court cases because they require that subjective judgment. This is heavily opinionated, as every judge will have their own sense of right and wrong which could conflict with different copyright laws. They provided an example about where a manufacturer of novelty cards made a parody of the children's dolls the Cabbage Patch Kids and used grotesque names and characters to poke fun at it. The judges ended up considering it a copyright infringement. (Source: [https://librarynews.blog.fordham.edu/2021/02/25/fair-use-week-2021/](url)

**Comment by julianjmg** [comment]
The article that I'm going to be highlighting is "Fair Use in the Real World" and something that I found interesting is how there isn't a particular formula and that certain things can be considered fair use for something that's not being used for educational purposes while another thing can not be considered fair use and be used for educational purposes. There are definitely a lot of factors in play and it comes down to a judge to determine if something is fair use.

Gray Area: While fair use is already pretty hard to determine w/o a judge, the fifth rule is where the jury and judge can determine if it's fair use based on their beliefs of what is right and wrong. This makes it even more unpredictable if the prior rules are in conflict with one another.

**Comment by jmp7651** [comment]
From reading "Measuring Fair Use: The Four Factors", one detail that surprised me regarding fair usage was regarding the amount of content you could copy from a source. You are essentially given the ability to take as much as you want from a source, albeit decreasing the chances of it being excused as fair use, as long as the "heart" (a key feature) of the product is not taken and utilized. However, this does not apply to parodies, as they use the heart of the original to develop a unique product based off it.

Gray Area: A gray area with fair use is the De Minimis defense, where the amount of copied material is so small that the court permits the usage of said material. The problem regarding this is that there is no way to determine if the amount of material taken is sufficient enough to utilize this defense. It relies on the court's decision on whether the amount is too small or sufficient enough to consider it a violation of fair use.

**Comment by tec5271** [comment]
From the reading, "Measuring Fair Use: The Four Factors", I found one part to be surprising but not at the same time because of how much sense that it makes. In the section labeled "The Nature of Copyrighted Work" they explain the leeway that exists when working with factual works compared to fictional works such as plays and novels. Another important factor to note is how the rules differ in fair use depending upon the status of the work. Meaning that if the work has been published the rules are a lot clearer and more lenient towards others looking to use them. On the contrary, if the work is unpublished they are almost untouchable because it is 100% the authors call on when the release of their information is allowed. 

Grey Area: One of the main grey areas that I saw in the reading was the fact that they say, the only way to get an exact ruling of judgment on these fair use situations is by going and appearing in front of a judge where they will use four factors to decipher whether the use of the works is fair or not. A second grey area that comes to light in this article is the issue that one can copy less and be better off than someone who copied a large portion of the text or whatever the usage is of. BUT if it is considered the "heart" of the work then the copying of that is a lot more punishable in the eyes of the court.

**Comment by tec5271** [comment]
> From the reading, "Measuring Fair Use: The Four Factors", I found one part to be surprising but not at the same time because of how much sense that it makes. In the section labeled "The Nature of Copyrighted Work" they explain the leeway that exists when working with factual works compared to fictional works such as plays and novels. Another important factor to note is how the rules differ in fair use depending upon the status of the work. Meaning that if the work has been published the rules are a lot clearer and more lenient towards others looking to use them. On the contrary, if the work is unpublished they are almost untouchable because it is 100% the authors call on when the release of their information is allowed.
> 
> Grey Area: One of the main grey areas that I saw in the reading was the fact that they say, the only way to get an exact ruling of judgment on these fair use situations is by going and appearing in front of a judge where they will use four factors to decipher whether the use of the works is fair or not. A second grey area that comes to light in this article is the issue that one can copy less and be better off than someone who copied a large portion of the text or whatever the usage is of. BUT if it is considered the "heart" of the work then the copying of that is a lot more punishable in the eyes of the court.

**Comment by ZakMurphy191** [comment]
Highlight a passage from any of the articles that surprised you about copyright infringement and "fair use": What surprised you?
~ The article that I found to be most interesting was, "Measuring Fair Use : The Four Factors". The section of "The Amount and Substantiality of the Portion Taken", will be my main focus in the article as I thought that it was super interesting that the amount you take can affect the outcome of copyright laws. In my own opinion I believe that any taken information that is not in your words or giving credit to the original owner shall be considered copyright and will be in violation. In this section they state that if you take a little amount it is considered fair use, but going back what is the difference of taking small amounts and large amounts when you are not giving credit? Say I came up with the idea of making an electric car and someone stole the idea and put the idea in another branded car how can you take half of the car the motor "heart" in other terms and call it your new idea and you custom built the electric car. When in reality I made the car and you took a little portion of the car and made it yours. I believe it is not fair to the owner for this to be okay. I do agree with every copyright conflict goes to federal court for the outcome of the specific problem, I just think they need to alter one thing and that is to have specific guidelines and not make it so free minded for the judges in court to decide.
Article: https://fairuse.stanford.edu/overview/fair-use/four-factors/
Identify one or two "grey areas" identified in the readings that can make copyright infringement unclear.
~ I believe that the four factors are the basis of the grey areas, I say this because the four factors are: 
- the purpose and character of your use
- the nature of the copyrighted work
- the amount and substantiality of the portion taken, and
- the effect of the use upon the potential market.
This shows how free minded a judge can be when making the decision of what's is right and what is wrong, and in many cases different judges contradict each other so you may go to two judges for the same copyright violation, and one might plead you guilty and the other may plead you of fair use. I just believe that there are not enough set rules for this and it is a major issue within the copyright world.

**Comment by jks6769** [comment]
From the article, "Measuring Fair Use: The Four Factors", something that surprised me was the use of copyrighted sources has to be used in a new or creative way, the purpose and character of your use of the sources have to have new meaning or expression. Your work essentially should be a transformation of the original copyrighted piece.

Gray Area: A gray area I found was in the fifth factor. The fifth actor is determined on the Judge and the Jury's sense of morality, If the Judge or Jury deems something wrong then they could make their decision against fair use.

**Comment by Yuying-Jin** [comment]
I am surprised with when people use other's artwork for an educational purpose and not in a commercial way, it belongs to fair use, because it would not harm the potential market for the author's work. Although fair use decisions rely on a balance of four factors, ensuring whether the use is reasonable is a very uncertain thing, and in many cases it still needs to rely on the judge's decision. 

In the case that Stephanie Lenz used Prince's Let's Go Crazy as background music for her video of her children dancing and running around in her kitchen, the copyright owner of the music removed the video from Youtube; however, after 6 years,  a district court ruled the copyright owner had no right to remove the video, since they did not undertake a legal analysis. We can the issue of legal uncertainty is very obvious.

**Comment by austinmurry** [comment]
The article "Fair Use in the Real World" was an interesting article to me. I have always heard about "fair use" and have heard many myths and such about what it is and when it's okay to use someone else's work vs when not too. I was under the impression that you could use others work for education related purposes and that if you modified the work in some way so it was not exactly like the original (mostly with music) then it was under the fair use category. This is sort of right as students and teachers are allowed to use work as long as it is for educational purposes and not to be sold or to make a profit. The thing I didn't know is that there isn't exact rules on fair use and it is kind of used "willy nilly", and that court cases are an important aspect of fair use.

The gray area that I can see is what is the limitation of the amount of a person's work you can use without getting claimed for copyright under fair use? The only way to really settle this is through a court case and even then things can still go one way or the other. This is the part of it all that still gets me to this day, and if you are to transform something, how much need to be transformed? Can I just enlarge someones nose and then its fair use?

**Comment by jeromenacey** [comment]
One of the articles that I read that contained an interesting fact about copyright infringement and "fair use" is in "Measuring Fair Use: The Four Factors". In it, under the fifth fair use factor part, I found that the judge or jury who was morally offended could decide against fair use depending on how they were able to rationalize it. What surprised me, sort of, was that the passage essentially said that the judge or jury would go against the Bill of Rights based off of if they were offended. At least, that's how it sounded to me, but I could be incorrect in how I interpreted it.
A gray area I read was in the same article, and passage, and covers the same topic as I have already stated. That is, the judge and jury's sense of morality would determine if you were incriminated or not. That could be a gray area as it depends on how a person interprets a case.

**Comment by gak5275** [comment]
The fact that the photograph in Case #4 of the third article was considered fair use surprised me. Who gets to decide what the "nature" and "purpose" of a photo is? If someone used a photo that I took without crediting me and/or asking for my permission, I would have a problem with that too.

Two gray areas/unclear implications about fair use I noticed:

In Case #1 of the third article, the music was supposedly obtained from a legitimate source. The only "legitimate source" could be the original seller, aka Capitol Records. Yet, the reselling of the records was considered unfair competition. This implies that it would be illegal to resell any form of media, which is untrue.

In Case #2 of the third article, _Oh, the Places You'll Boldly Go!_ was not considered to be a parody. Based on how it looks, how could it be considered anything more than a parody? It just looks like a Star Trek version of the classic Dr. Seuss book. Would it be better to make it more obvious or less obvious what is being parodied?

**Comment by als7294** [comment]
In the article by Wipo Magazine they say the following:
> "The uncertain legal status of remixes and mash-ups is the source of a great deal of frustration among members of the public. Few understand why the creative remixes they upload to YouTube are automatically taken down or blocked."

As someone with a large YouTube channel, I'm constantly battling YouTube's copyright flagging system, Many times I have had my video copyright claimed for generic sounds or quit background music. I also was a Twitch Affiliate, and I had to be very careful what songs I played in the background of my music. 

I found the following grey areas in the articles: There is no clear amount of time stated for how long you can use copyrighted content for on Youtube. Furthermore, after reading the articles I realized there needs to be a more clear definition of what makes a video a "parody" or not. For my film class, I had to make a music video. I lipsynced the song and made the music video very unique, yet YouTube still said it didn't qualify under fair use.
