### ISSUE TITLE
Mystery Text Discussion of jcb.txt

### ISSUE THREAD

**Issue by ebeshero** [newtfire/introDH-Hub#52]
Post your screenshots and findings about jcb.txt here!

**Comment by ipm5130** [comment]
![2022-03-22](https://user-images.githubusercontent.com/98833335/159519464-c0faf0b3-ed00-4277-93d4-bbb40ce52406.png)
![2022-03-22 (1)](https://user-images.githubusercontent.com/98833335/159519513-d60b6b7c-73c2-4424-9070-74af7b1904ad.png)
I would like to start with how incredibly interesting the voyant tool made a simple article look. In all seriousness, this was fun to look at and explore. The ngram sizes give me frequency counts above 5 were every number below five, what I mean is when I put the ngram on 4 it gives me freq. like 10 and 12. What's more interesting is when I put the ngram to size 3 it gives me a freq. of 109 at the highest, the phrase was I could not. 
I couldn't get much of the story, when I was reading I was trying to figure out what time does the story takes place. The way characters interacted you could tell they were children. Often they would say I could not, I can't, I don't, I am not, etc. as if they are defending themselves.

**Comment by TommyMC2** [comment]
I chose the text jcb.txt:

An n-gram size of 5 has one phrase with more than six uses, and that's "as well as i could," but with a size of 4, the highest is 12 with "in the course of."

"I could not" is repeated 109 times, and the next highest after that is "i did not" with 60




"Using KWIC on a few of the n-grams, I think the text is kind of dreary or at least solum a lot of the context of  "as well as I could" and "I could not" seems to be in that tone. The most common context to the "I could not" is the character discussing the problems they have to "bear" or endure.

I didn't find any references to violence, which leads me to believe this is more of a drama than I thought it might be at first, which was some fantasy adventure. I also respect the lack of repetition. Once you get past three-word phrases, repetition is very low, with the most repeated four-word phrase being "in the course of" 12 times. This text has 187,462 total words, and the most repeated one is Mr which I find funny because it demonstrates how much talking is done.
![Ant1](https://user-images.githubusercontent.com/124917672/225754754-030dc334-2ab0-4c7c-8acb-f614e0932fd6.png)
![Ant2](https://user-images.githubusercontent.com/124917672/225754757-5cc30692-d17c-4c83-94dd-b57a594b6016.png)
![Ant3](https://user-images.githubusercontent.com/124917672/225754760-7569804b-a656-4193-8179-95a6f8e4ecb1.jpg)
![Ant4](https://user-images.githubusercontent.com/124917672/225754761-2bdb1004-8ad5-404e-aa1b-707d6b141d5b.png)
![Ant5](https://user-images.githubusercontent.com/124917672/225754762-79e9abfc-27e0-40f8-b629-8ae02e060718.jpg)
![Screenshot 2023-03-16 171318](https://user-images.githubusercontent.com/124917672/225754764-e76eeb40-6786-4b8a-aa53-be74af4a85e4.png)
