### ISSUE TITLE
Mystery Text Discussion of ww.txt

### ISSUE THREAD

**Issue by ebeshero** [newtfire/introDH-Hub#53]
Post your screenshots and discuss your findings about ww.txt here!

**Comment by jms9354** [comment]
I chose this text, what I discovered is between using AntConc & Voyant tools was on AntConc the word "Martians" appeared 164 time, to where in voyant tools it appeared 163. I copy and pasted the exact same not sure why it was different. Also fascinating because I have no idea what the Mystery text is, but based off this I assume it has to do with martians or aliens of some sort. On AntConc the most common phrase was, "On the edge of the pit" which it appeared 4 times. To where on Voyant tools the most common phrase was, "amid the". Which appeared 11 times. I found this interesting because it shows each tool interprets the reading differently. I personally like different tools or views from Ant Conc & Voyant Tools, I feel as though Ant Conc is a little easier to maneuver to where Voyant tools is more vibrant and eye appealing with graphs and Cirrus.
I can't be for sure, but my guess would be the mystery text has to do with some type of invasion of aliens. It kept talking about a "pit" which appeared 83 times, and I've never heard of anything with a "pit" that turned out to be good. It also talked about "night" a lot which appeared 102 times. Usually with mystery or horror books and movies there's a big play of nighttime.

When I limited the results that only occur more than 5 or 10 times, The list got a lot smaller
![WW txtNGramSize2](https://user-images.githubusercontent.com/98782845/159366447-9e6ba277-54d7-4a1d-8926-39f3383819d0.png)
[TheComingOfTheMartians.txt](https://github.com/newtfire/introDH-Hub/files/8319337/TheComingOfTheMartians.txt)
![WW txtNGramSize3](https://user-images.githubusercontent.com/98782845/159366458-aa45e0c5-0eb2-451a-be8f-b6eaab8974ec.png)
![WW txtNGramSize4](https://user-images.githubusercontent.com/98782845/159366469-01d27088-654f-4d98-8055-217e8a55bcf9.png)
![WW txtNgramSize5](https://user-images.githubusercontent.com/98782845/159366477-3e1518b2-8cf5-4f41-934d-588a600358fc.png)
![WW txtNGramSize6](https://user-images.githubusercontent.com/98782845/159366507-8c23032d-9ce6-466d-aac5-545fb1b6f389.png)
![WW txtVoyant](https://user-images.githubusercontent.com/98782845/159366521-f6f56738-dd9c-402f-bd39-5646e1142f1d.png)
.

**Comment by JaxAbele** [comment]
There were a lot of interesting trends i noticed when looking at this text. As the n-gram gets higher the frequency of words and phrases becomes much smaller. at n-gram 5 there was only one frequency that was above 5. The frequencies became more common the smaller the n-gram got. Frequency counts in the double digits start at n-gram 4 and continue down to n-gram 1. There are no double digit frequencies in n-grams 5 and 6. The phrases "of the martians", "the heat ray", and "of the pit" are repeated several times throughout the text. I noticed that the word "said" is repeated the most during the passage which indicates to me that the plot could be driven by dialogue. The phrases "of the martians" and "the heat ray" being repeated so many times definitely indicates to me that this is a work of science fiction. 
![voyant](https://user-images.githubusercontent.com/98832721/159612961-f4339052-a012-4bc7-b9d5-295676620586.png)
![ngram5](https://user-images.githubusercontent.com/98832721/159612985-9eed1276-e36a-4589-a49c-a13bca8f9683.png)
![ngram4](https://user-images.githubusercontent.com/98832721/159612991-0042b4fa-f646-48c5-ad42-4c0e2480fe23.png)

**Comment by ghost** [comment]
The most interesting thing that I found when doing the analysis of this text is when the N-Gram Size was 3 there were two phrases the top of list, "a multitude of" and "a mass of". These two phrases imply a that a noun would follow and these would modify the quantity, however when the N-Gram size is 4 the phrases don't appear at all meaning that they all have different nouns that they are modifying(except "mass of red weed" appearing twice). 
![Quatifiy](https://user-images.githubusercontent.com/98792287/166083707-bfae8bdf-ba33-4d8e-b106-4d2a573598c6.PNG)
![Length of 4](https://user-images.githubusercontent.com/98792287/166083714-fa95b2d6-b946-45ba-a260-c256abdc965e.PNG)
The word martians is also the second most used word in the text. This must mean that the text is about martians in some way.
![WordCount](https://user-images.githubusercontent.com/98792287/166083732-ac5125e9-2f90-455f-b067-1c2f4e40a9fb.PNG)
