### ISSUE TITLE
Mystery Text Discussion of a radio play

### ISSUE THREAD

**Issue by ebeshero** [newtfire/introDH-Hub#55]
Post your screenshots and discuss your findings about any one of the texts in the radioPlays folder here!

**Comment by tfk5306** [comment]
![voyant tnt phrase](https://user-images.githubusercontent.com/98789268/159507473-aad3f7d5-4f94-4151-a12d-25e828aad617.PNG)
![antconc tnt](https://user-images.githubusercontent.com/98789268/159507490-2237a6fe-8722-47fc-b21a-03da8c088732.PNG)
[tnt01.txt](https://github.com/newtfire/introDH-Hub/files/8325241/tnt01.txt)
![voyant tnt01](https://user-images.githubusercontent.com/98789268/159507511-ed2f7c7c-63e0-4c81-ae6a-0afc22fc326f.PNG)
I feel like the two different programs looked at the text very differently because the data that it gave me was very different from each other. It is very different using the two different programs voyant is defiantly more user friendly but I believe that Antconc you can be more specific with the data that you want to collect.
