### ISSUE TITLE
Help! Can't get Git Bash to work 

### ISSUE THREAD

**Issue by ebeshero** [newtfire/introDH-Hub#6]
I can't get this to work. I tried this...
Here's some code I tried...

```
# markdown here
```
@ebeshero

**Comment by arrowarchive** [comment]
@ebeshero, I was able to submit the image to my repo, but it is not showing up under my commits. Is it because it takes a while, or is it because I did something wrong?

edit: it was because I typed the wrong thing. However, I have another issue: the image link is displayed, but the image itself won't appear when viewing the commit. Is there a way to view it automatically? 

Also, I don't know how to build up the site. Will this be discussed in class tomorrow? I'm asking because I am reading the syllabus to prepare.
