### ISSUE TITLE
Mystery text discussion of ww.txt

### ISSUE THREAD

**Issue by ebeshero** [newtfire/introDH-Hub#65]
Post your screenshots and discuss your findings about ww.txt here!

**Comment by Remdog712** [comment]
My findings were as follows
-N-grams 2 3 4 5 all had a frequency above 5.
-2 3 4 go past 10; 4 only reached 13.\
-I found that in Antconc: 
 
“..of the Martian..” shows up 28 times
“..of the pit…” shows up 26 times
“..out of the…” shows up 53 times

The phrases in Voyant with a frequency higher than 5 - 10 all were too vague I felt to give enough context.

From everything I gathered, the ww text file is a story regarding aliens coming to earth and either invading or making a home on earth. The use of words and phrases gives me a War of The Worlds vibe, but doesn't give me a clear plot or motive. Briefly scanning and skimming the text, I could pick up that there was conflict between people and the Martians. I like to imagine that it's not about a war but about a cohabiting story because the lack of death words or words associated with war. "Death" only showing up 38 times out of 60,442 total words. Could be accidental death or maybe even death unrelated to the possible conflict.


![bubblevoyatn2](https://user-images.githubusercontent.com/113142918/195696967-d0608705-498a-4e84-895b-7d6f5c62fdd3.png)

![bubblevoyant](https://user-images.githubusercontent.com/113142918/195696973-a401c7da-efd6-4d85-83b2-7ac9e9130f62.png)

**Comment by HadleighJae** [comment]
Above 5 n-gram: 
  2: 1467
  3: 313
  4: 33
  5: 1
Double digits n-gram:
  2: 541
  3: 65
  4: 3
Phrases often repeated: 
  The Edge of the Pit
  Of the Heat Ray
  The Martians
  Ulla Ulla Ulla
  My Brother
  The Artilleryman
From reading the text on both Voyant and AntConc, I wonder if this story is about the Martians trying to take over the world. There are many references to a military and potential battle going on, making me think the Earth is attempting to fight these Martians and protect the Earth. There is many references to a heat-ray, which I am assuming is a weapon used by the Martians to kill the people on Earth. I also assume the term "ulla ulla ulla" is a war cry the Martians use, or is possibly the language they speak and the author doesn't understand what they're saying. The author also makes references to his brother, who I assume he is fighting the Martians with. When it comes to the people of the world, they seem to be dying in large numbers. This is definitely a Sci-Fi novel about the Martians attempting to take over the world and the war that ensues with it. This is most likely from the POV of a normal man who later finds himself battling these aliens. 
![frequencywords](https://user-images.githubusercontent.com/113136860/196050953-f9de856c-3783-4651-beef-cc3628a2c5e4.jpg)
![heatray](https://user-images.githubusercontent.com/113136860/196050954-06787961-4d51-4d20-a2c4-40a2822080c0.jpg)
![martianscirrus](https://user-images.githubusercontent.com/113136860/196050956-69d9e7bb-9f61-4b56-85a4-94f0d28b2735.jpg)
![martiansvoyant](https://user-images.githubusercontent.com/113136860/196050957-518efc16-eddc-4db0-a53e-70e8f1f95116.jpg)
![mybrother](https://user-images.githubusercontent.com/113136860/196050958-21c84ede-2625-41dd-af4c-e3b550ea5876.jpg)
![peoplestory](https://user-images.githubusercontent.com/113136860/196050959-6f6b9fb6-7376-4548-b088-0d86affdc9d4.jpg)
![peoplevoyant](https://user-images.githubusercontent.com/113136860/196050961-40f3c789-64c7-463c-a566-9bd2155e6129.jpg)
![peoplewords](https://user-images.githubusercontent.com/113136860/196050962-fc103c46-ab14-4bd9-97f8-473d0952c72a.jpg)
![themartians](https://user-images.githubusercontent.com/113136860/196050963-ab5bd14d-c010-442b-90b3-d4dfb647db3a.jpg)
