### ISSUE TITLE
Mystery text discussion of cpi.txt

### ISSUE THREAD

**Issue by ebeshero** [newtfire/introDH-Hub#66]
Post your screenshots and discuss your findings about cpi.txt here!

**Comment by MinWu859** [comment]
image1: ![屏幕截图(124)](https://user-images.githubusercontent.com/61258632/196269620-58040630-8b31-4a4e-b3eb-2f6d8b741a03.png)
image2: 
![屏幕截图(125)](https://user-images.githubusercontent.com/61258632/196270023-ad65da5b-7719-4a50-a2a0-694d29445301.png)
image3: 
![屏幕截图(126)](https://user-images.githubusercontent.com/61258632/196270087-99197ec7-11db-47ff-9ecd-5c138f5add09.png)
 Through my studying and discovering in AntConc, I found that the larger the N-Gram size, the smaller the word's frequency. When I choose N-Gram size 1, the largest words frequency that appear in the text is "the"; the text has 3060 "the"; which means "the" is the highest frequency words in the whole text. The N-Gram size 5 and 6 have the word frequency that under "5", those words are the low frequency words within the text. The "KWIC" help me to see the lest content and right content of the selected words or phrase. This is very helpful for people who want to manage the word or to quickly find where the specific word or phrase is.

**Comment by mblankenberg25** [comment]
![Mysterytext2](https://user-images.githubusercontent.com/114019724/196491524-6b744aa7-5d5b-4627-b6bb-221f6e2b544a.jpg)
![mysterytext](https://user-images.githubusercontent.com/114019724/196491560-8c1c39ec-fda9-45ef-9b78-a8748fcb0033.jpg)
![mysterytext3](https://user-images.githubusercontent.com/114019724/196497180-5326e3f0-aca8-4ed1-a328-3de08151d400.jpg)

Frequent phrases:

of the - 330
the prime minister - 42
shook his head - 18
i don't know - 9 
the london and scottish bank - 6

In AntConc, I also found that the n-gram size increases, the word's frequency decreases. The words "the" and "of" are used the most in the text. I also noticed that the phrase "the london and scottish bank" is used quite often. I'm assuming that the text has something to do with money. The setting of the story seems to take place in Europe because of the references to the phrase "the prime minister". I am going to guess and say the story is about a bank robbery or detectives trying to backtrack a bank robbery.
