### ISSUE TITLE
Mystery text discussion of dc.txt

### ISSUE THREAD

**Issue by ebeshero** [newtfire/introDH-Hub#67]
Post your screenshots and discuss your findings about dc.txt here!

**Comment by JordanJ7** [comment]
I have noticed in ANTCONC with no restrictions to the ngram that there is an extreme amount of phrases such as "van Helsing" (322), "the professor"(150), "the door" (136). The most frequent phrase was "of the" (865). The KWIC phrase that I searched was "Van Helsing", from what appears to be a name that needs to be summoned such as summoning a demon or saying just an old falsified way of calling someone to another room. From what I can tell, this story has taken place a long time, and there is a doctor helping people.

Here are some exciting Finds 


![Screenshot 2022-10-17 210857](https://user-images.githubusercontent.com/114019891/196311803-275372d2-5937-4669-a505-1a7c5720a96e.png)

This shows one of the phrases that piqued my interest among all the other phrases and turns out to be just a name.

![image](https://user-images.githubusercontent.com/114019891/196311863-7c8370a9-e464-4b51-ad14-82a7a0857b56.png)

Here is a photo that shows what the most common words are with no restrictions.

**Comment by epp5198** [comment]
![antconc1](https://user-images.githubusercontent.com/112676517/196529956-428689e8-6d1f-463c-8025-80dbbce33efb.png)
![antconc2](https://user-images.githubusercontent.com/112676517/196531239-927643fe-1f5e-44f6-806f-5333315944a7.png)
While looking at this mystery text through AntConc I searched for an N-Gram of 3. The most common terms were "i could see"(73), "i could not" (68), and "dr van helsing" (67). While looking at "i could see" in KWIC it showed many interactions between the main character of the story and others signifying that the character is some sort of professional from the surrounding dialogue.
