### ISSUE TITLE
Mystery text discussion of radio play

### ISSUE THREAD

**Issue by ebeshero** [newtfire/introDH-Hub#68]
Post your screenshots and discuss your findings about one or a group of radio plays here!

**Comment by ghost** [comment]
Worried for my guy John and Horace in Anesthesia.txt. It felt like it was maybe a poem about anesthesia, though it could be something much more sinister. Then I am reading the sentences around the names and it literally reads like some deranged murder/assisted suicide. 
 
<img width="1245" alt="Screen Shot 2022-10-17 at 8 48 18 PM" src="https://user-images.githubusercontent.com/82339806/196309916-0ffc00fa-e618-4eff-9c10-1026b692997f.png">

Weird as hell. 

Also it is cool that both programs pick up the same most used words. But that's probably just because they have the same general programming and whatnot. 

<img width="1338" alt="Screen Shot 2022-10-17 at 8 41 47 PM" src="https://user-images.githubusercontent.com/82339806/196310005-d30dd81c-4077-4c44-ac74-9770c292961d.png">

Besides that I think the best n-gram size for something like a story is 3. It gives you a general gist of what is in the story without having you read the whole story. I'm sure for like scientific manuals and stuff a smaller or larger n-gram size is more appropriate depending on the subject material.

<img width="1244" alt="Screen Shot 2022-10-17 at 8 39 07 PM" src="https://user-images.githubusercontent.com/82339806/196310122-eeba4513-ea07-4462-9eb8-361b30d8363c.png">

**Comment by SavannahRicks** [comment]
The text I randomly chose was an interesting one. When I saw the first word to show up in the word cloud to be "peg," I was like "huh?" But as I explored more of the context I discovered that it was a name of one of the main characters in this story. The reason this name, and others, pop up the most is because its a script for a play.  The name shows up everytime that charcter is speaking or doing an action. I also saw that the word "sound" was a big part in the script. I learned by the context of "sound" that this play is suspencful and mysterious. By increasing the n-gram in AntConc, I found out that Pegs full name is Peg Lincoln, and that she is trying to solve some mystery with a couple others.
![Screenshot 2022-10-19 170431](https://user-images.githubusercontent.com/112633511/196806962-104df22b-bc53-4d95-bf8c-40f05f629c8c.png)
![Screenshot 2022-10-19 170949](https://user-images.githubusercontent.com/112633511/196806992-57f457f5-29a9-47eb-ac18-656924703e94.png)
