### ISSUE TITLE
Workshopping Websites

### ISSUE THREAD

**Issue by ebeshero** [newtfire/introDH-Hub#7]
Post links to your websites in progress here in this issue if you'd like to get some viewer response. Include any commentary or questions about things you'd like to do or add or change!

**Comment by arrowarchive** [comment]
@ebeshero, this is the link to my current GitHub website: [The Arrowarchive](https://arrowarchive.github.io/The-Arrowarchive/)

I plan to create thumbnails for my pictures that redirect to individual tabs for the image, changing my layout, and showing my profile picture on front page (and I really want to do the last one, since I mentioned it on my FAQ, but I don't know how to do that/if I can do that with my current theme)

Here's the link to the wordpress as well: [The Arrowarchive Wordpress](https://sites.psu.edu/arrowarchive/)

I've been having issues with adding pages and links. I have one for each, but neither are showing up on the main page.

**Comment by ebeshero** [comment]
[Link to my site](https://newtfire.org/courses/introDH/comparativeWebAssign.html). I'd love to know what you think of the color choice and fonts here. Should I change my headings? Do you notice any errors?

**Comment by am0eba-byte** [comment]
[do the click to get my git](https://am0eba-byte.github.io/personal-remote-repo/)
[and also my Wordpress](https://sites.psu.edu/mborgiadigportfolio/)
I definitely want to put more into my GitHub pages, but I'd appreciate feedback on any aspect of both of them. Be as cruel and critical as you'd like

**Comment by NickyV1234** [comment]
[my psu site that i have very little work done on but its still something](https://sites.psu.edu/nickdig100/)

**Comment by ebeshero** [comment]
@arrowarchive and all interested in image display issues.  Here is some code that you can adapt to alter the display size of your image on your webpage:

```
<img src="images/yourImage.jpg" alt="Girl in a jacket" width="20"/>

```

**Comment by ebeshero** [comment]
This HTML code is equivalent to the markdown for images, only it gets you more detail:
```
![Girl in a jacket](images/yourImage.png)
```

**Comment by ebeshero** [comment]
How to link a thumbnail (small image) to [a larger image](url): 


```
Example Link code: [thing you are linking whether image or text](images/yourImage.png)

```

Thumbnail linking to full-size image:
```
[<img src="images/yourImage.jpg" alt="Girl in a jacket" width="20"/>](images/yourImage.png)

```
