### ISSUE TITLE
Mystery Text discussion of a Radio Play

### ISSUE THREAD

**Issue by ebeshero** [newtfire/introDH-Hub#76]
Post your screenshots and discuss your findings about one or a group of radio plays here!

**Comment by ebeshero** [comment]
(Reminder: Don't do ac.txt b/c we did that in class on Tuesday March 14, so it's no longer a big mystery.) This response is just here as a demonstration of a comment in GitHub Issues. I found this interesting pattern in which "laughter" is a super large word in the Voyant wordcloud (cirrus) view of ac.txt. 
![Screenshot 2023-03-14 at 13 01 00](https://user-images.githubusercontent.com/4014518/225081650-ec007d15-6f43-4ba0-9031-1bb924f14a49.png)

**Comment by cbl5678** [comment]
I did the text "generalmaxwelltaylor.txt." Ngrams 3 and 4 both produce frequency counts above 5. Ngram 3 produces some as high as 20. Ngram 3 is the only ngram that produces frequency values in the double digits. When you reach ngram 4, there is no longer any frequency values above 5. Some of the most frequent phrases are "do you think" and "general taylor i." 

This text is an interview of General Maxwell Taylor. The way the text is written, we get a lot of repeated words because it labels who is speaking each time, like in a play. The interview tends to talk alot about armies and war.  Without reading the text fully im having trouble determining what war they are talking about and where exactly General Taylor is from.

<img width="1440" alt="3_ngram" src="https://user-images.githubusercontent.com/125323277/225697571-23eb04f8-b189-4dd9-b622-4522b331c767.png">

<img width="476" alt="most_used_words" src="https://user-images.githubusercontent.com/125323277/225697591-94263a53-9485-402a-82b3-6450a1a4133f.png">

<img width="1440" alt="do_you_think" src="https://user-images.githubusercontent.com/125323277/225697601-4e9f79db-1a1c-4f13-9752-2ca304974112.png">

<img width="1440" alt="4_ngram" src="https://user-images.githubusercontent.com/125323277/225697611-c6db4647-7c5e-4274-a1e8-f14fadaac32c.png">
