### ISSUE TITLE
Mystery Text discussion of pcc.txt

### ISSUE THREAD

**Issue by ebeshero** [newtfire/introDH-Hub#78]
Post your screenshots and discuss your findings about pcc.txt here!

**Comment by ebeshero** [comment]
![newt-mosaic4](https://user-images.githubusercontent.com/4014518/225694219-8b40db18-949b-4e35-8002-4eae67b9b2b3.png)

**Comment by mew-II** [comment]
pcc.txt was certainly an interesting story to look at through AntConc and Voyant's eyes. Both pointed out different perspectives, AntConc looked at repeated words and phrases which lead to some interesting out of context statements like the ones seen in this screenshot:
![deathByViolence](https://user-images.githubusercontent.com/124916317/225695441-7c4aafa1-34ad-4d4d-973a-1f2d90ed6900.jpg)
My favorite of which is definitely "thrown into the water immediately after death by violence." I love how it contrasts with the two that follow about a nice garden. And somehow also works with the repeated "ugh(s)" that precede it.

Voyant seems almost critical of the text pointing out the severe lack of vocabulary differentiation. In the top five words used Said and Say are both present.
![lackOfVocabulary](https://user-images.githubusercontent.com/124916317/225696524-d2a1b936-b9c3-48b5-a365-35f95b399f77.jpg)
I assume that most people will also post this but I thought I'd include it regardless as it shows off the vocab usage pretty effectively.
![words](https://user-images.githubusercontent.com/124916317/225697149-83a5ccab-1381-4743-890e-e94bff685954.jpg)
The two perspectives together leave a lot to fill in on my own, due to the high amount of say and said, I expect a large dialogue focus in the text, and based on the content of the text I assume there is some sort of murder or battle that occurs at some point in the story. The Author uses very basic dialogue which makes most of the low ngram word clouds look like an English teacher's "Don't use these phrases/words" poster. Finally, I also noticed that phrases, even ones up to 10 words in a row were repeated up to 3-4 times, I have no idea why this would be.

**Comment by ceq5032** [comment]
<img width="1228" alt="Screenshot 2023-03-16 at 12 32 48 PM" src="https://user-images.githubusercontent.com/125389208/225693959-13f1fa69-f3cb-4a23-bee1-a6cd24fa042d.png">![image](https://user-images.githubusercontent.com/125389208/225694034-a41c083f-eb58-4d78-b588-36dc2af7d2aa.png)
<img width="1039" alt="Screenshot 2023-03-16 at 12 30 52 PM" src="https://user-images.githubusercontent.com/125389208/225694398-6c8e0d84-e5d2-440f-a734-54631fc5a745.png">![image](https://user-images.githubusercontent.com/125389208/225694775-f188e2cd-4c0d-408a-b39c-d5998a0f7c63.png)
<img width="1106" alt="Screenshot 2023-03-16 at 12 48 38 PM" src="https://user-images.githubusercontent.com/125389208/225694917-90336bf8-72c1-4cb8-996b-9013b62663d3.png">![image](https://user-images.githubusercontent.com/125389208/225695711-dfcfec69-5d52-4312-9505-6388e9e1be2d.png)
<img width="1106" alt="Screenshot 2023-03-16 at 12 47 31 PM" src="https://user-images.githubusercontent.com/125389208/225696069-563fab2e-5fff-4c79-bd4f-d45bbbdc2a95.png">![image](https://user-images.githubusercontent.com/125389208/225696900-40244c4e-9619-482b-9cca-bbcde32c271d.png)
<img width="1090" alt="Screenshot 2023-03-16 at 1 08 09 PM" src="https://user-images.githubusercontent.com/125389208/225698385-5ab31192-ecbe-4c71-9df7-64069443cc71.png">![image](https://user-images.githubusercontent.com/125389208/225698427-0042fe20-8e81-4ddb-93b2-2c7c57bb3194.png)

**Comment by sammoniot** [comment]
Something about the text that I found intriguing was that the word "great" had a continuous decrease in the number of times used throughout the document. This makes me think that things were possibly getting worse over time or "less great." 
![Screenshot (14)](https://user-images.githubusercontent.com/124915674/225808318-1129d316-a283-4230-9ae8-6bf16bf7b5a3.png)


In addition, as the ngram increased, the lower the frequency got. 
 
![Screenshot (12)](https://user-images.githubusercontent.com/124915674/225807882-b566301d-70d2-42a4-b987-ad674f1abbd6.png)
![Screenshot (13)](https://user-images.githubusercontent.com/124915674/225807884-1c9efd36-0731-43bd-b5a5-09c54bed7e95.png)



Another part of the document that I found interesting was that the phrase "time out of mind" appeared nine times. That phrase is not used very often in recent years. The only thing that I could think of is a 1997 Bob Dylan album with the same title. 
 
![Screenshot (15)](https://user-images.githubusercontent.com/124915674/225808246-ccb31a1c-c36f-4823-8cc2-6c0f4e490066.png)


Another word that is not used very often but was used twenty-eight times was "thence" which further reminds the reader of the time period that was probably written a long time ago. 
![Screenshot (16)](https://user-images.githubusercontent.com/124915674/225807991-f3ccc6cf-58c2-457e-a233-9dbb47b69ddd.png)
Looking through the document and analyzing its texts has reminded me about how the words we use can change over a small period of time.
