### ISSUE TITLE
Mystery Text Discussion: lrt.txt

### ISSUE THREAD

**Issue by ebeshero** [newtfire/introDH-Hub#87]
Post your screenshots and discuss your findings about lrt.txt here!

**Comment by macmiller8600** [comment]
<img width="600" alt="Screen Shot 2023-10-31 at 12 29 19 PM" src="https://github.com/newtfire/introDH-Hub/assets/146369612/ee6226ef-67b9-4178-af84-18c5e2ca92cb">
<img width="600" alt="Screen Shot 2023-10-31 at 12 34 44 PM" src="https://github.com/newtfire/introDH-Hub/assets/146369612/e6c75a9f-6aa4-4138-ae37-5540a42faf8d">
<img width="600" alt="Screen Shot 2023-10-31 at 12 37 20 PM" src="https://github.com/newtfire/introDH-Hub/assets/146369612/8e377121-fe6e-40f0-87c0-f4092c22bb98">

I recently dived into some text analysis using both Voyant and AntConc, and let me tell you, it's like two sides of the same coin. Voyant Tools, it's all about the big picture, with its cool word clouds and trend analysis giving you the lowdown on the most talked-about themes. But AntConc, that's where the magic happens when you want to get up close and personal with the text. It's all about those concordance analyses and collocations, showing you exactly how the words are playing out in their own little worlds within the text. In AntConc, I stumbled upon the phrases, "in the shire" and "of the shire," popping up quite frequently. In Voyant, on the other hand, I actually had to go on a little hunt to find it. I even upped my N-Gram on Antconc to 5 words, and ‘in the shire’ didn't even show up in the top ten. When you combine the two sites, it gives you two different views of the same text, and makes you think more.

**Comment by morgs2005** [comment]
![Uploading Screenshot 2023-11-20 at 9.02.17 PM.png…]()

<img width="1440" alt="Screenshot 2023-11-20 at 8 54 32 PM" src="https://github.com/newtfire/introDH-Hub/assets/146490172/2c6d4652-79c6-4d6a-a69c-ce2cd995af11">

I chose this file randomly. I personally really like Voyant because of how many options pop up on screen to see. There are words and a graph to show the words used. Antconc to me seems more confusing. I feel like it is confusing because I really don't know how to use my Mac.
