### ISSUE TITLE
Mystery Text Discussion: cpi.txt

### ISSUE THREAD

**Issue by ebeshero** [newtfire/introDH-Hub#89]
Post your screenshots and discuss your findings about cpi.txt here!

**Comment by Rkd5429** [comment]
For the reoccurring words within the text, I listed them from most common to least common within the top five most reoccurring words within the text. 1: “Poirot” 475 times, 2: “said” 205 times, 3: “Mr” 166 times, 4: “Man” 158 times, 5: “Little” 116 times. As for the Ngrams, AntConc was only able to find two lines that reoccurred above five times with an Ngram size of five. Reducing that number to four, found 25 lines that at least reached five or went slightly beyond that. I’ll be ranking the Ngrams just as I did the individual words. 1: “I don't know” 9 times, 2: “Poirot shook his head” 7 times, 3: “That the prime minister” 7 times, 4: “at the same time” 6 times, 5: “I beg of you” 6 times.
![Screenshot 2023-10-31 153959](https://github.com/newtfire/introDH-Hub/assets/146772937/c8771e61-956d-49f4-aae3-b8bea889d900)


Lowering the Ngram size down once more from four to three, we break into double digits. The highest frequency Ngram was “the prime minister” which appeared 42 times.

The three KWIC clusters that I chose were “I don't know”, “The prime minister”, and “Poirot shook his head”.

The first thought in my mind when I had to choose a text was that I needed something that would lead me to questions which would then let me understand the text in general depending on the questions asked. So that led me to use “I don't know”. As it turns out, this did not help at all. I put in “I don't know” and I left knowing about the same amount as every person who said "I don't know" in the story. 
![Screenshot 2023-10-31 145437](https://github.com/newtfire/introDH-Hub/assets/146772937/2c4e2480-fc50-4dae-9b83-5573e5e6db0b)


The second text, unlike the first, was more helpful in understanding a portion of what the story could be about. “The prime minister” was the second Ngram that I chose and it gave me six hits that helped me understand that the prime minister was kidnapped and perhaps impersonated by a member of the group who kidnapped him. The crime happened within one or two vehicles and it happened before the prime minister was supposed to leave for some event.
![Screenshot 2023-10-31 145541](https://github.com/newtfire/introDH-Hub/assets/146772937/e7f41863-1c34-4ca3-ba3c-2cad268fe081)


The third text suggested that there was some correlation to France. Either the story took place there or someone is from the country. I can only assume that this person is Poirot. Mainly because the Ngram I used for this one was “Poirot shook his head”. Within the seventh hit, he even combines French and English within the same sentence. Poirot is also a significant character within the text. The KWIC hits don't really make that apparent but the frequency of his name within the text suggests that he is. Poirot appeared a total of 475 times within the text which when we refer back to the singular word count from the first paragraph, is the highest occurring word within the text.
![Screenshot 2023-10-31 145930](https://github.com/newtfire/introDH-Hub/assets/146772937/1f1565e1-f1cb-414a-b297-c4f624b116b8)

**Comment by ebeshero** [comment]
I like how you systematically tested these ngrams to try and understand what kind of text you are looking at. And it's funny how you studied the "I don't know" ngram to see what kinds of things people don't know in the text! I think "the prime minister" gave some helpful clues here...
