### ISSUE TITLE
Mystery Text Discussion: cpi.txt

### ISSUE THREAD

**Issue by ebeshero** [newtfire/introDH-Hub#99]
Post your screenshots and discuss your findings about ww.txt here!

**Comment by njp5577** [comment]
From this text document (cpi.txt), frequencies above 5 occur at ngrams sizes 5 and below. Sizes of 3 and below for the ngram give frequencies in the double digits. In terms of common phrases, they are mostly composed of references to locations and characters relevant to the text (Poirot, the Prime Minister, London, and so on).

![digittext1](https://github.com/newtfire/introDH-Hub/assets/115658656/2422fef5-e695-41a8-a482-2e0bb19546e2)

![digittext2](https://github.com/newtfire/introDH-Hub/assets/115658656/7dbcced1-8267-4427-9095-b01c68052c17)



Some common phrases are also mixed in there for high frequencies. One thing I found interesting was the common use of "I don't" as well as " I do not". They are close to the same frequencies at ngram size 3. Looking at the direct uses of "I do not", I think that these are intentionally used to portray the level of formality the character is speaking in (whether or not they heavily use contractions while speaking). I am assuming this, because the text samples include a lot of "Mr.", "Miss", "Mrs.", and other more formal descriptors. One the other hand, analysis of how "The Prime Minister" is used seems to indicate that he is being watched or maybe even investigated.

![digittext3](https://github.com/newtfire/introDH-Hub/assets/115658656/24fcf3e4-eb16-417d-acef-74b65d90f919)

![digittext4](https://github.com/newtfire/introDH-Hub/assets/115658656/fa528062-ea13-4f8b-b4e6-4327499b95e9)



From the few text snippets that I have seen and the text analysis results, I can piece together that this is some sort of detective story. I wonder what the general plot of the story is.
